### ISSUE TITLE
Remove Cesium Installer From PRGM Menu

### ISSUE THREAD

**Issue by matthew17754** [mateoconlechuga/cesium#10]
It appears that the Cesium program in the PRGM menu simply serves as an installer for the most part on first use or to install stability files to archive. However, after the Cesium installer has been run, the Cesium PRGM cannot be archived or removed as it will throw an ERROR when launching the "A" PRGM. Will a fix be released so that the user can remove the Cesium PRGM and still use the shell by running "A"? It just would seem more convenient to have only one thing on the PRGM menu instead of "Cesium" and "A". Or perhaps consider having just one program on the PRGM menu that installs and runs the shell. Just to clear up space on the PRGM menu, ya know. Thank you for your consideration. ;)

**Comment by mateoconlechuga** [comment]
Of course it can't be removed. This issue is closed.
