### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#100]
I have been using the newest version of Cesium, and I noticed a few minor bugs:
1) If you are at the top of the settings list and you scroll up, the cursor disappears.
2) If a GarbageCollect needs to be run in order to archive something, Cesium simply won't archive it.
3) Renaming AppVars makes them 10 bytes bigger (I'm not positively sure about this one)

**Comment by mateoconlechuga** [comment]
Thanks for the reports :)

**Comment by mateoconlechuga** [comment]
Fixed with a4fab27297c61ca102194637e830ae7af066564e, 6cbd65f801a5a9679ffdc54e3e249445b49f20d2, and 13f38cb9dbbbfa0e58eb091636f4a49b5750b95a.
