### ISSUE TITLE
Menus don't restore home

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#101]
Simply put, `menu(` doesn't restore the home after being used.  You may have to run it from Cesium twice to make it (not) work.
![menu(](https://user-images.githubusercontent.com/47825483/58480108-9b41d000-8127-11e9-9824-8afcc1ae4da6.png)
The code seen here is the bare minimum, programs that use menus and rely on the restoration of the previous screen ([MathTools](https://www.cemetech.net/programs/index.php?mode=file&id=1349)) are affected.

**Comment by mateoconlechuga** [comment]
Fixed with 4255bf834c83e3678e35c19141a47385e032121f
