### ISSUE TITLE
All errors return to Cesium

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#102]
I was not able to reproduce this in CEmu, but my physical calc is suffering from this.
Every error returns to Cesium, whether it is on the home screen, or in a program, they all return to Cesium.  I have a few ideas how this could be fixed, but no idea how it began… Yet.

**Comment by mateoconlechuga** [comment]
It's probably from using 3.1.1. Resetting your calc and using 3.1.2 or later should fix this.
