### ISSUE TITLE
Suggestion: Disable running BASIC programs in settings

### ISSUE THREAD

**Issue by slimeenergyreal** [mateoconlechuga/cesium#103]
I've had some glitchy things happen with BASIC programs, and would like a way to disable running TI-BASIC programs in Cesium. An option in settings that's disabled by default would probably be the best way to go about doing this. You could also have an option that goes next to the program sub-menu with archived, locked, and hidden.

**Comment by mateoconlechuga** [comment]
The point is to fix the basic program issues, not disable them. Please report actual issues.

**Comment by mateoconlechuga** [comment]
In other news, there is a new pre-release (3.1.3) that should hopefully fix your basic program issues.
