### ISSUE TITLE
Mode and Format menus inaccessible from Cesium editor

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#104]
The mode and format menus are inaccessible from the Cesium editor.
![Bug-2](https://user-images.githubusercontent.com/47825483/58749885-5dabb280-8459-11e9-8100-b4c130d9e023.png)

**Comment by mateoconlechuga** [comment]
Fixed with bb1c7fa47b8bb500a61769568ef6d5f088074fe4
