### ISSUE TITLE
Backspacing doesn't work

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#105]
The title says all.
When creating or renaming a program, backspacing doesn't function as it should, there are other things related to this, but I believe by fixing this you fix the other issues as well.
![Bug-3](https://user-images.githubusercontent.com/47825483/58749944-0823d580-845a-11e9-913e-ba6381012e89.png)
For reference here's the other main bug having to do with this:
![Bug-4](https://user-images.githubusercontent.com/47825483/58750061-584f6780-845b-11e9-9e3d-b86e9ec6d8bb.png)
Renaming (or creating) a program to be more than 8 characters internally resets the selector.

**Comment by mateoconlechuga** [comment]
Fixed with 584e3e0f08540cf9eba9627472e6fac35dc08168
