### ISSUE TITLE
On shortcuts in certain menus causes instability or resets

### ISSUE THREAD

**Issue by ZombieGenius** [mateoconlechuga/cesium#109]
Specifically, using it in the catalog help menu causes weirdness, while using it in the randInt( menu resets RAM.

**Comment by ZombieGenius** [comment]
Steps to reproduce: 
1.) select randInt( in math menu
2.) use shortcut (on+pgrm, on+stat)

**Comment by mateoconlechuga** [comment]
Are you using the latest pre-release?

**Comment by calclover2514** [comment]
I can reproduce these with the following (on a real calc, v3.1.5).
Catalog bug:
1. Go to the catalog
2. Press [+]
3. Press [on], [prgm]
4. Press [clear]
5. Press [UP]

randInt crash:
1. Go to the randInt( menu
2. Press [on], [prgm]

**Comment by mateoconlechuga** [comment]
I can't reproduce the `randInt(` crash, but I do get the first one's weirdness.

**Comment by mateoconlechuga** [comment]
I fixed the first one, but just to point out how ridiculous TI is, if you go to the mode menu, and then click go directly to the `randInt(`, the menu doesn't appear :P

**Comment by mateoconlechuga** [comment]
Fixed with bfc8f6072e8e0f2d386dd337667d4a522f2a9842
