### ISSUE TITLE
Error in Displaying program language

### ISSUE THREAD

**Issue by SM84CE** [mateoconlechuga/cesium#11]
![cesium230_errors](https://user-images.githubusercontent.com/32180916/30722216-c7c68200-9ee4-11e7-83e9-33dd8eb13d04.gif)

**Comment by SM84CE** [comment]
Seems only C prgms are affected...

**Comment by PeterTillema** [comment]
Confirmed this. It seems to be an issue if the program has an icon, then it displays the wrong language string.

**Comment by mateoconlechuga** [comment]
The issue is that C programs didn't display the correct string. Fixed :)
