### ISSUE TITLE
Installer Validation Failed

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#111]
The installer installs Cesium just fine, and it still works, but when it tries to run Cesium after the installation is finished, it throws an "Error: Validation" error.
I can still run Cesium from the apps menu and everything else works perfectly, but the installer is incapable of running Cesium (and yes, even I can tell this is nitpicking a little bit :P).

Also, is there any way you can have the installer delete Cesium before installing instead of just telling me it can't install the new version? Thanks.

**Comment by mateoconlechuga** [comment]
Well that's odd. You may have to clear out the archive, sounds like something made it get corrupted.

**Comment by calclover2514** [comment]
It was my OS.
Upgrading to OS 5.4 fixed it.
