### ISSUE TITLE
Label jump accepts invalid labels

### ISSUE THREAD

**Issue by ZombieGenius** [mateoconlechuga/cesium#113]
The label jumping menu (on + graph) accepts invalid labels, such as Lbl ! (which displays as a -), Lbl Lbl, or even a label inside of a string ("Lbl A"). 
Steps to reproduce:
1. Make BASIC program with erroneous label (any special character, name longer than 2 characters, inside of a string, etc.)
2. Run Cesium
3. Edit program using Zoom
4. Open label jump menu using On + Graph

**Comment by mateoconlechuga** [comment]
There is literally no way to detect that, so this is acceptable behavior.

**Comment by mateoconlechuga** [comment]
Also those are not invalid (ICE uses such labels).

**Comment by calclover2514** [comment]
Plus, labels inside of strings would be useful for jump points in programs without using up a label.

**Comment by mateoconlechuga** [comment]
I'll fix the display of tokens I guess. And the offsets if a label is in a string so it is properly positioned.

**Comment by mateoconlechuga** [comment]
Fixed and a new release is available.
