### ISSUE TITLE
Cursor resets to APPS folder instead of "APPS" program

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#114]
Creating, editing, executing, and renaming a program (to be) named "APPS" causes the cursor to reset to the "APPS" folder.

![Apps](https://user-images.githubusercontent.com/47825483/59151413-af77ae00-8a00-11e9-810e-4e8c3fb771a7.png)

Edit: This also occurs when renaming an AppVar.

**Comment by mateoconlechuga** [comment]
I hate you <3
