### ISSUE TITLE
Deleting Cesium Appvar and Exiting the Settings Menu Causes Reset

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#115]
Deleting Cesium's Appvar and exiting the settings menu causes a reset. (See title)
![AppVarNo](https://user-images.githubusercontent.com/47825483/59152403-43517600-8a11-11e9-9306-bf69c0a0d134.png)
(Apparently CEmu didn't want to capture the reset…)

Possible fixes:
* Preventing the user from deleting the Cesium Appvar
* Recreating the Appvar every time it exits the Settings menu, not just edit the Appvar.

**Comment by mateoconlechuga** [comment]
Thanks.

**Comment by mateoconlechuga** [comment]
It now checks if the appvar exists and creates it if it doesn't.
