### ISSUE TITLE
ON+Prgm shortcut uses up >65,000 bytes of RAM, but only in Classic mode

### ISSUE THREAD

**Issue by ZombieGenius** [mateoconlechuga/cesium#116]
Steps to reproduce: 
1. Set calculator to classic mode (mode, up, right, enter, clear)
2. Use Cesium shortcut (ON + Prgm)

**Comment by mateoconlechuga** [comment]
lol

**Comment by ZombieGenius** [comment]
Also happens when using ON + Prgm while editing a program normally, regardless of mode.

**Comment by mateoconlechuga** [comment]
Fixed with release 3.1.7.
