### ISSUE TITLE
Folder icon background doesn't change fully

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#118]
The new folder icon looks perfectly fine on a white background, however there are bits of the icon that are white or very bright rather than transparent, therefor there are parts of the icon that don't look that great on different colored backgrounds.
Example with a fixed version: https://i.imgur.com/VJnUZh2.png

**Comment by mateoconlechuga** [comment]
fixed with b1bbbdcdc11ffe3fd779c47b6f6133c5f776ce14
