### ISSUE TITLE
Label finder in F-menu causes graphical errors

### ISSUE THREAD

**Issue by ZombieGenius** [mateoconlechuga/cesium#119]
Steps to reproduce:
1. Edit program using Cesium
2. Open an F-menu (e.g. F5 using alpha + graph)
3. Use label finder (ON + graph)
(4). Jump to label (unless no labels are present in the program)

**Comment by mateoconlechuga** [comment]
will you stop.

**Comment by ZombieGenius** [comment]
I'm sorry

**Comment by adriweb** [comment]
must. find. all. the. bugs.

**Comment by mateoconlechuga** [comment]
fixed with 1c88a6971a7a7fc8e920dc0f411e9837a644c5fe
