### ISSUE TITLE
Label jumping (ON + Graph) doesn't work if program is edited using Goto from an error

### ISSUE THREAD

**Issue by ZombieGenius** [mateoconlechuga/cesium#120]
<3
Steps to reproduce:
1. Run program
2. Cause error (ON will do it)
3. Choose goto
4. Attempt to use Label Jump (ON + Graph)

**Comment by mateoconlechuga** [comment]
Note: This only happens when the program is run from Cesium.

**Comment by mateoconlechuga** [comment]
fixed with 853eda1083f374b3e025ef3e0cc3255a89863b14
