### ISSUE TITLE
Breaking out of a program while in an Input and in the Catalogue causes the catalogue to stay open

### ISSUE THREAD

**Issue by ZombieGenius** [mateoconlechuga/cesium#121]
1. Create a program with the code Input "",A
2. Launch it in Cesium
3. Press 2nd then 0 to access catalogue
4. Press ON, then choose quit
5. Launch the program again
Now you're in an invisible catalogue.

**Comment by mateoconlechuga** [comment]
Fixed, but I probably won't make another release until I see some more critical bugs :P
