### ISSUE TITLE
Hiding + Renaming can give programs the same name

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#122]
By hiding files you are really just renaming them, because of this, Cesium sees the two (hidden and unhidden) as different programs, in this way, you can create multiple programs with the same name as seen below:
![sthv](https://user-images.githubusercontent.com/47825483/60029641-8a757300-966f-11e9-9925-7ab386fe3700.png)
![sdg](https://user-images.githubusercontent.com/47825483/60029557-66199680-966f-11e9-8bd7-3c1d4efaf25c.png)
This can cause problems as seen here:
![gfhd](https://user-images.githubusercontent.com/47825483/60029764-bd1f6b80-966f-11e9-8ce1-3a886efec965.png)

**Note:** This bug has been around since the first releases.

Also, can the right arrow be added as an alternate way to enter the properties menu and the left arrow to exit the properties menu?

**Comment by mateoconlechuga** [comment]
It's not a bug.

**Comment by mateoconlechuga** [comment]
Fine.

**Comment by mateoconlechuga** [comment]
The left and right keys will eventually open a menu for usb things.
