### ISSUE TITLE
Make `0` transparent in icons

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#124]
As `B` is already `WHITE`, `0` should be transparent to help icons adjust to the Cesium background theme

**Comment by mateoconlechuga** [comment]
I don't even understand what you are saying.

**Comment by calclover2514** [comment]
Right now, in :DCS icons, the following colors are true:
```
0=WHITE
1=BLUE
2=RED
3=BLACK
4=MAGENTA
5=GREEN
6=ORANGE
7=BROWN
8=NAVY
9=LTBLUE
A=YELLOW
B=WHITE
C=LTGRAY
D=MEDGRAY
E=GRAY
F=DARKGRAY
```
It would be better if `0=Transparent` instead of `0=WHITE`

**Comment by mateoconlechuga** [comment]
I disagree. If someone wanted portions of their icon to be white; now if you change the background color it will no longer be white.

**Comment by calclover2514** [comment]
Is this issue worth reopening? Because you closing it makes me unable to reopen it.

**Comment by mateoconlechuga** [comment]
added with 1331784
