### ISSUE TITLE
OS App Description Displays Incorrect Version Number

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#127]
I'm not sure if this is fixable, but:
![Capture 1](https://user-images.githubusercontent.com/43104632/61603559-07aeec00-ac0c-11e9-9a2a-829a72a38086.png)

**Comment by mateoconlechuga** [comment]
That's not an app version. That's the minimum OS version that the app can run on.

**Comment by LogicalJoe** [comment]
It should be `5.0.0.0000` to be consistent with the other apps, right?
