### ISSUE TITLE
Numerous Cmds launch Cesium

### ISSUE THREAD

**Issue by jcsq6** [mateoconlechuga/cesium#130]
Cesium launches after attempted use of several tokens. I first noticed this when using the "horizontal" command in the draw menu. Then I noticed many others, mainly in the stats menu. For example, I needed to find the line of best fit of L1 and L2. After entering my data through the "LinReg(ax + b)" I was sent right to Cesium's GUI. The same thing happened with all of the other tokens. This also led to some interesting bugs... like being able to move a cursor around on the home screen and see x and y coordinates. Good luck! I have no clue...

**Comment by LogicalJoe** [comment]
Currently, this sounds similar to #102 where errors open Cesium.  If this is the case, try deleting and reinstalling Cesium.  If that does not fix the issue, try resetting the calculator.
I was unable to reproduce this problem, so if this does not fix it, please provide some example code so we can parse it and figure out what may be happening.

**Comment by mateoconlechuga** [comment]
I can't reproduce this. If you have some steps on how I can, that would be great.
