### ISSUE TITLE
Pressing the [del] key when renaming a file

### ISSUE THREAD

**Issue by beckadamtheinventor** [mateoconlechuga/cesium#132]
Pressing the [del] key when renaming a file causes Cesium to freeze.
How to reproduce:
- press [graph] on a file.
- enter some text.
- press [del] to backspace.
- Enter more text [Optional]
- press [enter] to rename when happy with the name.
- freeze and be sad.
- force-crash out. [Optional]

**Comment by beckadamtheinventor** [comment]
EDIT:
Just try to rename a file. Freezes.

**Comment by mateoconlechuga** [comment]
Duplicate of #131
