### ISSUE TITLE
Odd Renaming/Making Files Glitch

### ISSUE THREAD

**Issue by Argus1234** [mateoconlechuga/cesium#133]
I have found an interesting glitch; when renaming/creating files, if you press the back arrow key, the name of the file will be corrupted, and some interesting graphical glitches will appear all over the screen. I don't know what causes this, but it sometimes causes my calculator to crash.

**Comment by mateoconlechuga** [comment]
I think you may be using an old version of Cesium, because I cannot reproduce this on version 3.2.0. Thanks for the report!
