### ISSUE TITLE
Power off with password on wake doesn't work when plugged in

### ISSUE THREAD

**Issue by joshuathooyavan** [mateoconlechuga/cesium#134]
Hi there! Just wanna say that I'm loving Cesium so far! 

The shortcut [on]+[stat]  doesn't turn off the calculator as expected when plugged in to a computer. Not really a huge issue, but just something I noticed.

**Comment by mateoconlechuga** [comment]
Thanks for the report, but unfortunately I can't do much about this one. I also wanted to make sure that the password feature was bypassable in case someone forgot it.
