### ISSUE TITLE
Suggestion: Add support for folders

### ISSUE THREAD

**Issue by K4rakara** [mateoconlechuga/cesium#135]
Would be nice to be able to organize programs within folders. 
Now obviously, the TI 84 + CE doesn’t let you have folders or organization of any kind. 
However, there’s no saying that it couldn’t be done. Specifically, you could make a appvar with a table containing lists of folders and what files are in said folders. Then, in Cesium, only load the files that are “in” those folders by checking the table. 
If this gets implemented, it would probably be best to give the “special” folders (IE Apps and AppVars) their own icon and the “go up one folder” a unique icon.
Thanks for making Cesium in general by the way, it’s a great shell, and without it we’d all have to use TI-OS.

**Comment by LogicalJoe** [comment]
Mateo himself said somewhere (likely in the Cemetech thread) that he will not implement folders (also see #26).  The only way folders will be added to Cesium is if you implement them yourself.  If you want folder support anywhere in the near future, don't ask when DoorsCE will be released, and use a different shell.

**Comment by adriweb** [comment]
From a technical standpoint, the traditional way to implement folders is not usable anymore (an unused byte somewhere is now used by the OS). Sure there could be alternative ways to do that but it's more work that's probably not worth it for most.

**Comment by K4rakara** [comment]
Ah! Sorry, I didn’t know that the developer had already said anything, I don’t frequent the camitech forms. 
Although with the GitHub issue that has already been closed, that’s on me for not checking.

**Comment by mateoconlechuga** [comment]
Okay I'll do it but it'll take a while

**Comment by mateoconlechuga** [comment]
Nope too weird.
