### ISSUE TITLE
.8xp file cannot be found

### ISSUE THREAD

**Issue by Riolu2Lucario** [mateoconlechuga/cesium#138]
Matt, I have used the find file button and went through all the folders and can't find the .8xp file. could you tell me what i am doing wrong?

**Comment by Riolu2Lucario** [comment]
I have downloaded both the master and the usb versions and cant find the .8xp file

**Comment by Riolu2Lucario** [comment]
please help me

**Comment by Riolu2Lucario** [comment]
Please help me matt

**Comment by Riolu2Lucario** [comment]
or someone who knows how to recover an .8xp file from a github download

**Comment by adriweb** [comment]
What are you talking about?
The 8xp file is inside the release archive (.zip) that you download from https://github.com/mateoconlechuga/cesium/releases/latest
