### ISSUE TITLE
Suggestion: Add combined size as size on folder

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#139]
As of right now, when you hover over a folder, it just shows 000000 under size. It would be cool if it instead displayed the combined size of every item in the folder so you could tell how much space a certain thing takes up (E.G. Appvars).

**Comment by mateoconlechuga** [comment]
No, too much extra parsing. I'll just remove the entry.

**Comment by mateoconlechuga** [comment]
Closed with 8af4d670642b56f581dc48960ed3cd0fb04ac7e8
