### ISSUE TITLE
BASIC program execution errors

### ISSUE THREAD

**Issue by SanjivanM** [mateoconlechuga/cesium#14]
When I executed the following code:
```
[CLASSIC]
Lbl A
Input Str0
If Str0="..":Goto Q
Goto A
Lbl Q
[MATHPRINT]
```

The program hangs, without switching to MATHPRINT.  A few seconds later, when the Run indicator stops spinning, I pressed [ON], which caused the RAM to reset.  Another thing is that when I ran a test version of BonziCE, the input field looked weird: (the picture was taken w/ TI-Connect CE, when the cursor was "off".  The plot mark wasn't there before.  Also, the homescreen is a bit messed up when I ran BonziCE (input Field is lower, the $ is the start of the field).  The homescreen was cleared before the Input.

Error picture: 
![bonzice error](https://user-images.githubusercontent.com/33943333/33191296-176bd7ee-d075-11e7-9a50-1fff82634cf0.png)

**Comment by mateoconlechuga** [comment]
Fixed with 84097eb
