### ISSUE TITLE
Turning off calculator while editing a program from Cesium breaks things

### ISSUE THREAD

**Issue by ghost** [mateoconlechuga/cesium#140]
Using Cesium 3.2.2.

Steps to reproduce:
1. Open Cesium
2. Edit a program from Cesium
3. Open any menu (i.e. prgm menu)
4. Press 2nd, then ON to turn off the calculator

This will stop the calculator from turning back on (until reset).

**Comment by LogicalJoe** [comment]
Nice find!  I used to have this problem a lot, but when I went to report it I could never figure out how it happened.  And after a few more "random" freezes I just started exiting cesium before turning off the calculator.
