### ISSUE TITLE
Folder Management

### ISSUE THREAD

**Issue by jcsq6** [mateoconlechuga/cesium#142]
A little nit-picky thing for lack of clutter... when moving from project to project I don't like seeing multiple programs in the program list, it feels all cluttered and noisy. Anyways, I think a massive improvement to the app would be to add some type of folder management. It wouldn't have to be super extensive- just enough to get those projects on the back burner out of the way. I hope to see this implemented! It would be an awesome improvement!

**Comment by mateoconlechuga** [comment]
I can't see a good enough reason for this. Even when creating TI-BASIC programs I would always call my program `A` so I could quickly access it when developing.

See #26 and #135
