### ISSUE TITLE
cannot run cesium in TI-SmartView

### ISSUE THREAD

**Issue by datiti** [mateoconlechuga/cesium#143]
On TI-SmartView simulator for TI83 premium CE (os 5.4.0.0034), when running cesium v3.2.2 for the first time:
```
Asm(prgmCESIUM + ENTER
```

The simulator gets **freezed** on a clear screen with a **yellow circle** on the top right corner.

Can you please help?
kind regards
cyrille

**Comment by mateoconlechuga** [comment]
This is a TI-SmartView issue, not a Cesium one. It is impossible to support.
