### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DuneSciFye** [mateoconlechuga/cesium#144]
Whenever I have a syntax error or any kind of error, including when a program is not working, I'm sent to the cesium page. Is there any way to fix this? Also I can't access a program called allmath.zip because of cesium.

**Comment by adriweb** [comment]
- What would you like to happen instead?
- That seems normal and unrelated to Cesium. Transfer calculator files, not zip files. So, extract your zip archive first, then transfer 8xp/8xv files etc.

**Comment by DuneSciFye** [comment]
Is there a way to make it so that instead of sending me to the app, it just shows the error? And I also fixed the second problem.

**Comment by mateoconlechuga** [comment]
You need to disable hooks in the Cesium settings. And then you can enable them later.

**Comment by DuneSciFye** [comment]
Thanks that fixed it!
