### ISSUE TITLE
USB Flash Drive (Program?) Crashes Calculator

### ISSUE THREAD

**Issue by BioHazard1282** [mateoconlechuga/cesium#147]
When you load up Cesium, it shows a USB Flash Drive ez80 program in the program (folder). When selected, it crashes.

Tried with:

TI-84 Plus CE
OS 5.3.0, 5.3.1, 5.4, 5.4.1
Hardware: 5.1.5

**Comment by mateoconlechuga** [comment]
This is unreleased functionality. Delete your Cesium AppVar and reinstall. The flash drive will no longer be visible.
