### ISSUE TITLE
Cesium resetting memory when trying to install. 

### ISSUE THREAD

**Issue by reachomk** [mateoconlechuga/cesium#148]
On trying to install Cesium, it resets my calculator's memory.  I am on OS 5.6.0.0020 with boot code 5.1.5.0014. I am using arTIfiCE to try to install it.

**Comment by adriweb** [comment]
Are you sure to have the very latest Cesium version? An older version won't work. Download it here: https://github.com/mateoconlechuga/cesium/releases/latest

**Comment by reachomk** [comment]
Interestingly, extracting it and then opening it in TI Connect worked instead of dragging it from the zip into TI Connect.
