### ISSUE TITLE
ClrHome, Input, and sub( are causing a crash

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#152]
Reproduced using [APOLYF10](https://www.ticalc.org/archives/files/fileinfo/458/45849.html).
On input within this program you can get a bugged input line (appears to have something to do with the `ClrHome` right before it).  If you input a 1-character string on this line and don't press clear to reset the field the program will DOMAIN error with only one option: Quit.  Selecting this option will corrupt the screen and cause a reset.
![cesium](https://user-images.githubusercontent.com/47825483/93842313-6afb3a80-fc64-11ea-86b2-e746490e3c27.png)
The OS, on the other hand, will jump to the function `sub(Str0,2,length(Str0)-1)` in the line following the input.

Would fix myself and pull if I knew how the code worked, haha.

**Comment by mateoconlechuga** [comment]
So the OS is being super dumb and not giving the right stuff. I fixed the crash among other things with cadc007, but there will still be no "goto" option available. I think this is okay though, so I'm going to close it. If you have time, give it a try and let me know if there are any other bugs.
