### ISSUE TITLE
Add invert colors support.

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#155]
Now that OS 5.6 no longer allows AsmComp, people can no longer make the program that allows you to create a sort of 'dark theme' by inverting the colors. You mentioned potentially adding this into Cesium so I made an issue to ensure you didn't forget. :) 
The post for the invert colors code is [here](https://www.cemetech.net/forum/viewtopic.php?p=282252#282252).

**Comment by mateoconlechuga** [comment]
Inverted colors can now be enabled via the `on`+`sto` shortcut in 3.4.1
