### ISSUE TITLE
Hiding then archiving prgma or prgmc bricks the calculator

### ISSUE THREAD

**Issue by commandblockguy** [mateoconlechuga/cesium#160]
Hiding then archiving prgma or prgmc bricks the calculator.
Steps to reproduce:
1. Create prgma or prgmc, with a lowercase letter for the name. This is left as an exercise for the reader.
2. Find prgma/prgmc in Cesium, then press alpha to open the properties menu.
3. Select hidden, then archived.
4. Exit Cesium.
5. Enjoy your paperweight.

**Comment by BioHazard1282** [comment]
> Hiding then archiving prgma or prgmc bricks the calculator.
> Steps to reproduce:
> 
> 1. Create prgma or prgmc, with a lowercase letter for the name. This is left as an exercise for the reader.
> 2. Find prgma/prgmc in Cesium, then press alpha to open the properties menu.
> 3. Select hidden, then archived.
> 4. Exit Cesium.
> 5. Enjoy your paperweight.

Bricks? So it cannot boot again or do you have to re-install the OS?

**Comment by mateoconlechuga** [comment]
Fixed with 475c4dd
