### ISSUE TITLE
Dark mode shortcut should toggle dark mode, not only set it + set on startup?

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#165]
Another issue because yes.

Also could it be a startup feature?

**Comment by TheLastMillennial** [comment]
I can't quite make sense of this title. I assume I'm encountering the same issue where launching Cesium immediately inverts the colors. Also, making [on]+[sto->] a toggle would be very nice indeed.

**Comment by LogicalJoe** [comment]
No, the second part is a request for it to be set on power up alongside the passcode feature if it was set on power down.

**Comment by mateoconlechuga** [comment]
I can't read the SPI so the `sto->` key can't really act as a toggle, so instead I used the `ln` key to reset it. I also can't make things persistent on power cycles unless I modify the OS, so for now I'm marking this as closed

**Comment by LogicalJoe** [comment]
Like the passcode feature, is it not possible to append reading the invert bit and inverting if necessary on startup?

**Comment by mateoconlechuga** [comment]
I just said I can't read the invert bit.

**Comment by LogicalJoe** [comment]
Oh.  I thought the value was cached somewhere to allow Cesium to unset invert and reset it on exit if necessary.  My bad.
