### ISSUE TITLE
Displaying and clearing the graphscreen restore text that should not be on the homescreen

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#168]
![trash-absolute trash](https://user-images.githubusercontent.com/47825483/109593172-7f2e4800-7ade-11eb-844a-e1841c4a9227.png)
Bit of an odd one, not sure how to provide more information than the screenshot - try it for yourself.
Ignore ti.plotSScreen being full of garbage, that's not really a bug (I think).
Tested in Cesium 3.4.1.

**Comment by mateoconlechuga** [comment]
Fixed in another commit; but also fixed the plot screen being filled with garbage.
