### ISSUE TITLE
Password Bypass

### ISSUE THREAD

**Issue by coolcrab123** [mateoconlechuga/cesium#17]
As we all know, the TI 84 CE displays a message about how you should plug your calculator in to avoid RAM deletion, when it is in the "red" zone of the battery cell. When this is the case, and you shut down your calculator with the Cesium Password Tool (ON|STAT), The Calculator turns off properly. However, when turning it back on, The Calculator first Displays the Password Entry Field, and then switches to the "YOUR BATTERY IS LOW" Notification, when you click any button to get rid of the notice, the TI 84 CE no longer displays the password request, bypassing it, and giving you full control of the calculator.

Respond by Sending a Message to me Through my New Website: coolcrab123.wixsite.com/coolcrab123

**Comment by jcgter777** [comment]
What do you mean by "full control of my calculator"? Is it like I can edit anything I want on there? or is it that it disables Cesium's hooks?

**Comment by adriweb** [comment]
He means that it bypasses the Cesium password feature, so you can do whatever as if there were no password. Then sure, you can probably edit settings etc.

**Comment by SanjivanM** [comment]
You can also just plug the calc in whenever, I had to do that in class b/c my password got "reset" (my code, nor "5555" the default, wouldn't work).

**Comment by jcgter777** [comment]
You need TI-Connect CE to "refresh" your calculator's contents, I thought.

**Comment by SanjivanM** [comment]
Yes, that is true, I haven't tried a plug into the wall yet...

**Comment by jcgter777** [comment]
(Go on cemetech)I'll delete this

**Comment by coolcrab123** [comment]
Yes that is what i meant. Also, plugging your calculator into the computer will also bypass the password feature, as it forces the calculator to turn on.

**Comment by mateoconlechuga** [comment]
It's too hard to fix this. The password feature is more of a novelty than anything else, not really meant to secure it that much.
