### ISSUE TITLE
"ERROR: UNDEFINED" with Stop token

### ISSUE THREAD

**Issue by RoccoLoxPrograms** [mateoconlechuga/cesium#172]
When a TI-BASIC program is run within Cesium or after any program has been run in Cesium, if a Stop token is at the end of the program (I realize that it's not very good practice to put a Stop token at the end of a TI-BASIC program), then the OS throws "ERROR: UNDEFINED". This only happens in Cesium or after a program has been run in Cesium.

**Comment by mateoconlechuga** [comment]
I can't seem to reproduce this -- closing for now until steps to reproduce are given :)
