### ISSUE TITLE
Exit label hook jump menu without jumping + jump to line?

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#175]
Exit label jumper because sometimes I realize I don't need it and amp to line because sometimes I didn't put a label and just happen to know what line something is.

**Comment by mateoconlechuga** [comment]
Added the ability to exit without jumping; I don't think it's worth adding a "jump to line" because line numbers are weird in basic.

**Comment by Legend-of-iPhoenix** [comment]
Maybe something more useful is a "jump to the character you were at when you exited the editor last"?

**Comment by mateoconlechuga** [comment]
That's what the return does now :P
