### ISSUE TITLE
Cesium not dealing with the homescreen properly

### ISSUE THREAD

**Issue by Michael2-3B** [mateoconlechuga/cesium#178]
Not exactly an important issue, and can be easily fixed by adding a ClrHome to the TI-Basic program. But I thought I'd leave this report here.

In the 1st case, having entries on the homescreen and then running my program doesn't make the homescreen entries shift up like they should.

In the 2nd case, editing any program in Cesium and then running my homescreen program leaves the program code behind on the screen, when it should be completely clear, or rather displaying what's already on the actual OS homescreen.

![NotClearingHomescreen](https://user-images.githubusercontent.com/34347626/116505421-75c42080-a880-11eb-925f-7446bbc47351.png)

**Comment by mateoconlechuga** [comment]
And your program is?

**Comment by mateoconlechuga** [comment]
Cesium will now clear the homescreen before running a program
