### ISSUE TITLE
Random tokens appearing on rename menu

### ISSUE THREAD

**Issue by Michael2-3B** [mateoconlechuga/cesium#179]
This is a very specific bug that I have only gotten to occur on rare occasion, and thus I cannot recreate it consistently or identify any probable cause. The only constant I know here is that it is always with a program that has an 8 character long name.

The bug is that hitting rename on such a program displays a bunch of random tokens, that even wrap to the other side of the screen.

See here:
![rename](https://user-images.githubusercontent.com/34347626/117531454-28466280-afa8-11eb-908e-44d5f4f7f9fe.jpg)

**Comment by darkwater4213** [comment]
Can reproduce. I've got this on occasion myself -- I thought it was jus a glitch, not an actual bug. I guess the multiple recurrences should've clued me in -- hah!
