### ISSUE TITLE
Cesium install

### ISSUE THREAD

**Issue by bcdozierJW** [mateoconlechuga/cesium#183]
Sorry, but I'm a retired IT guy but new to TI-84 CE. I understand TI messed-up but I'm trying to get my new TI-84 CE Plus to be as easy to use as my TI-89. I understand about the ASM problem. I've downloaded and installed the Cabri Jr and Artifice programs. But how do I get the Cesium files into the TI-84? I've tried several iterations of Cabri & Artifice off or on but when moving any of the Cesium files over TI-Connect complains. Moreover, exactly what do I transfer?

**Comment by mateoconlechuga** [comment]
What OS are you using? You should just be able to download the zip file here: https://github.com/mateoconlechuga/cesium/releases/download/v3.4.1/cesium.zip

Extract the zip and then send `cesium.8xp`. You have to send the file when the calculator is at the homescreen; and can be sent in TI-Connect CE via the `Actions > Send to Calculator` drop-down menu or by dragging and dropping the file onto the calculator itself in TI-Connect CE.

**Comment by bcdozierJW** [comment]
Thank you for taking the time to reply.
TI reports 5.6.1.

What I downloaded from the link you included was very different from what I had downloaded before. I have Cesium on my calculator but 'Cesium' displays Cesium and  Deriv with lock symbols and Radical without a lock symbol. Now what?

The other Cesium download had folders 'Include' and 'src' and 5 other misc. files. The 'src' folder, as you probably know, has many asm files. However, attempting to move one of the asm files to TI-Connect gets the "We don't like you" error message.

I thought Cesium contained the programs to return some of the functionality of the TI-89.

Or maybe I'm confused. Where do I find programs to run under Cesium?

(I don't know what happened to the TI-89 development team but whoever replaced them must not use hand calculators.)

bcdozier
Copar

**Comment by adriweb** [comment]
Well as Matt said earlier, you only have to send the 8xp file from the zip, nothing else (the asm files are the source code, you don't transfer those).

Once transferred, you'll just have to launch the Cesium program (which is the installer) on the calc itself (a bit annoying for the first time because of TI blocking ASM, so you'll have to use arTIfiCE to launch it). Anyway, once launched, Cesium will install itself into the APPS menu so it'll stay there even after a ram reset or hard reboot. From Cesium (the app) you can launch any asm program.

**Comment by mateoconlechuga** [comment]
You probably just downloaded the source code (that's what this repository is for). You can download releases available here: https://github.com/mateoconlechuga/cesium/releases (the latest one is always [here](https://github.com/mateoconlechuga/cesium/releases/latest))

**Comment by bcdozierJW** [comment]
Thank you for taking the time to respond to my emails, but I've given up. I'm positive Cesium is correctly installed as I have access to the 2 settings pages. But the only apps listed under Cesium are the apps that came with the 84-CE and, of course, Cesium.
I tried to move one of your asm files to the calculator while at Home Screen while Artifce was running and while Cesium was running. Connect always responded with the 'Get Lost' message. This is version 5.6.1 of the OS. Maybe TI has done a work-around you!

So, I'm looking on ebay for a TI-84 CE and inquiring as to which operating system is installed. And then I'll call Walmart and tell them my little sob story and see if they will let me return the unit. Had I purchased it from Amazon, as I usually do, there would be no problem.

Again, I appreciate your time in trying to assist and Thank You!

bcdozier
Copar

**Comment by mateoconlechuga** [comment]
Wait, sorry, are you asking how to install other programs? What programs are you looking for in particular? Cesium is just a shell for launching assembly, C, and other types of programs.

**Comment by mateoconlechuga** [comment]
You can download a lot of programs at the below links, and send them to your calculator with TI Connect CE when at the homesecreen:

https://www.cemetech.net/downloads/browse/84pce
https://www.ticalc.org/pub/84plusce/
https://tiplanet.org/forum/archives_cat.php?cat=ce

**Comment by commandblockguy** [comment]
You can't directly send .asm files using TI-Connect CE, you need to use an assembler to assemble them from their source form into .8xp binaries you can send to the calculators.
That said, there's no need to build the .asm files in this repo yourself, as they are just the source files for cesium.8xp which you already have installed. Practically all programs for the CE provide .8xp binaries to download, so there's really no need to touch the .asm files yourself unless you want to edit them.

I've made a video explaining how to use arTIfiCE here, which you might find helpful: https://youtu.be/_e8pgw9d7S4

**Comment by bcdozierJW** [comment]
Thank You, Thank You, Thank You. I'm running some of the math programs you pointed me too.

Still....I like the T-89 better.

**Comment by adriweb** [comment]
Well yes the 68k calculators (89/92/v200) and the CAS Nspire models are much better for math, since they have a CAS engine :)
