### ISSUE TITLE
Error when first installing

### ISSUE THREAD

**Issue by EzraCerpac** [mateoconlechuga/cesium#184]
When I tried to install cesium on a TI-84 Plus CE-T I got an error that said: "Attempted to use a variable or function where it is not valid."

**Comment by adriweb** [comment]
Looks like you need to use the [arTIfiCE jailbreak](https://yvantt.github.io/arTIfiCE/)?

**Comment by EzraCerpac** [comment]
Yes, I didn't now that was a thing. Thank you
