### ISSUE TITLE
password doesn't work

### ISSUE THREAD

**Issue by minecraftcrush6** [mateoconlechuga/cesium#188]
TI-84 Plus CE Python
OS: 5.6.1.0012 (jailbroken with arTIfiCE)
Cesium: 3.4.1

**Comment by adriweb** [comment]
Can you give more details as to what you've tried and doesn't work exactly?

**Comment by mateoconlechuga** [comment]
No details provided, closing until more details are provided.

**Comment by minecraftcrush6** [comment]
on+stat seems to lock it but turning the calculator doesn't

**Comment by mateoconlechuga** [comment]
on+stat is what you use to lock it. There is no "power-on" password feature.
