### ISSUE TITLE
Change "edit" key & other stuff

### ISSUE THREAD

**Issue by SanjivanM** [mateoconlechuga/cesium#19]
Maybe change the edit key to one that doesn't have a letter on it?

Also, when I pressed [PRGM] to open the editor, the 3 lines of my 3 line prgm were at the top, minus the "PROGRAM: name" line.  Also, there were random tokens at the bottom of the screen (bottom 6ish lines).  Those tokens disappeared after I pressed [enter] a few times to add new lines into my prgm.  Tested on CEmu.

**Comment by mateoconlechuga** [comment]
*sigh* DO NOT REPORT ERRORS WHEN THEY ARE NOT RELEASED. FINAL WARNING.

**Comment by mateoconlechuga** [comment]
Man I was a jerk. Sorry :(

**Comment by SanjivanM** [comment]
No problem, apology accepted
