### ISSUE TITLE
[ON] shortcuts not working.

### ISSUE THREAD

**Issue by CyberFinn69** [mateoconlechuga/cesium#190]
I have the TI-84 Plus CE-T (Python Edition) running OS 5.6.1 and the latest version of Cesium. The [ON] shortcuts don't work for me, none of them. Even if they are turned on in the settings.

**Comment by mateoconlechuga** [comment]
Are you holding the [on] button? What is the date code/revision number on the back of the calculator?

**Comment by CyberFinn69** [comment]
I don't know what happened, but somehow it suddenly works. Thanks for the help and sorry for wasting your time.

**Comment by adriweb** [comment]
Glad it works now, however we're still interested in the characters on the back of your calculator (for documentation purposes), too the right of the serial number. It should look like "L-0621T" or something like that. 
Thanks!

**Comment by mateoconlechuga** [comment]
You didn't waste my time lol. That's what these issue things are for

**Comment by CyberFinn69** [comment]
> Glad it works now, however we're still interested in the characters on the back of your calculator (for documentation purposes), too the right of the serial number. It should look like "L-0621T" or something like that. Thanks!

L-0421S

**Comment by adriweb** [comment]
Awesome thanks!
