### ISSUE TITLE
Can't find FATDRVCE/USBDRVCE

### ISSUE THREAD

**Issue by rafalou38** [mateoconlechuga/cesium#191]
When I try to access the USB functionality cesium asks me to download FATDRVCE/USBDRVCE but I searched everywhere and didn't found it.

**Comment by darkwater4213** [comment]
> These libraries are currently unreleased and may undergo some slight revisions. I would greatly appreciate it if you can give them a try though and let me know if you have any issues interfacing with a USB drive.

I have downloaded these libraries in hopes of being able to access a 1GB SD disk (which I did format as FAT32). My setup looks like this:
TI-84+CE    <=>    USB Mini A to USB Mini B cable    <=>    A Sony USB Mini B disk reader (supports SD, Mini SD, MMC, MS, and Duo -- Model # MRW62E-T, if that helps)    <=>    SD to Micro SD Adapter    <=>    The actual 1GB Micro SD chip

Cesium keeps returning the "No FAT32 Partitions found!" error whenever I try to connect. Why? Do I just need a more direct connection (without going through three different adapters)? Or is it the libraries, or my calculator?

**Comment by mateoconlechuga** [comment]
I haven't tested any SD cards. Use a flash drive like a normal person.

**Comment by darkwater4213** [comment]
I would, but the only adapter I have for that has a USB Micro plug, not a USB Mini A or USB Mini B (I'm not sure which one it ought to have). So I can't use it... :( 

Looks like I'm going to have to blow that six bucks to get the one off of Amazon, I guess.
