### ISSUE TITLE
Allow description for basic programs

### ISSUE THREAD

**Issue by mateoconlechuga** [mateoconlechuga/cesium#195]

**Comment by Bryankaveen** [comment]
So, will it be possible?

PS: Seems that Adriweb didn't translate everything in Cesium (french version), can I help ?

**Comment by adriweb** [comment]
> PS: Seems that Adriweb didn't translate everything in Cesium (french version), can I help ?

It as complete at some point, but maybe new things aren't translated - feel free to open a PR modifying [the strings here](https://github.com/mateoconlechuga/cesium/blob/master/src/strings.asm#L201)

**Comment by mateoconlechuga** [comment]
Added in adb6704. More information can be found [here](https://github.com/mateoconlechuga/cesium/blob/master/icons_descriptions.md).

**Comment by Bryankaveen** [comment]
Thank you very much Mateo !!! 😀
