### ISSUE TITLE
[Feature Request] An option to turn off auto−graph clearing when executing a program in Cesium.

### ISSUE THREAD

**Issue by ShinyTillDawn** [mateoconlechuga/cesium#196]
I was testing a TI−Basic Program in Cesium trying to find coordinates to place certain shapes, but every time I close that program on Cesium, the graph screen gets cleared! I can tell this is probably intentional, so therefore I'm not reporting this as a [i]bug.[/i] However, I would like if there was an option to leave the graph screen intact so that I can run programs on Cesium and break out of it so I can easily look at what's drawn on the screen to be informed on what coordinates I should locate objects in. Perhaps the nature of Cesium covering the entire screen makes this impossible...

**Comment by mateoconlechuga** [comment]
fixed with c878fab
