### ISSUE TITLE
"Please insert a FAT32 formatted drive" when the usb drive is connected

### ISSUE THREAD

**Issue by 3miner6379** [mateoconlechuga/cesium#197]
The usb drive i had problems with is a SamData USB Flash Drive which i got of amazon exactly from here: https://www.amazon.com/dp/B08CRMBD93?ref=ppx_yo2_dt_b_product_details&th=1
i formatted the usb drive to Fat32 and installed CE C for usb so cesium could use the drive but an error message was saying "Please insert a FAT32 formatted drive"  which i did and its connected firmly. however when i tried another usb drive i had specifically a SanDisk Cruzer Glide USB Flash Drive. that time cesium could access it and i could run ASM programs from it.

**Comment by 3miner6379** [comment]
Yeah, the one i got was the 8GB one.

**Comment by mateoconlechuga** [comment]
I got the samdata drive and tested it right out of the box and it worked fine. Are you sure you are using MBR partitioning and a FAT32 filesystem?

**Comment by 3miner6379** [comment]
Yes i did format the usb drive to fat32 and it has a MBR. but maybe i did something wrong?

**Comment by mateoconlechuga** [comment]
Was able to reproduce your issue on hardware. It appears that the USB drive does not conform to the spec. Will post fix soon.

**Comment by 3miner6379** [comment]
alright, many thanks!

**Comment by mateoconlechuga** [comment]
hopefully fixed via https://github.com/CE-Programming/toolchain/commit/40101d4e075c7e96180a11728dd4110aacd3e9c8
