### ISSUE TITLE
Two Bugs/Feature Requests

### ISSUE THREAD

**Issue by BruceTheShark42** [mateoconlechuga/cesium#200]
Hello,

I've also noticed two things that may or may not be intentional. First one is you can't switch back to light mode from dark mode by using `on`+`sto->` again. I found myself automatically trying swap back and found that I couldn't without turning it off and on again.

Second, folders can display different file information depending which folder it is.
![All Progams](https://user-images.githubusercontent.com/50778347/139527687-04f51345-db6e-429a-b6d8-516390b597c3.png)
![Apps](https://user-images.githubusercontent.com/50778347/139527688-5f91f4fe-6659-4ab5-ae94-a03d9fb82822.png)
![AppVars](https://user-images.githubusercontent.com/50778347/139527689-dcc4352e-97ab-4298-b0cf-274bcef69dad.png)

**Comment by UInt2048** [comment]
> First one is you can't switch back to light mode from dark mode by using on+sto-> again.

That one's intentional: the shortcut to swap to light mode is `on` + `ln`

**Comment by BruceTheShark42** [comment]
I can't seem to get `on`+`ln` to work for some reason even though `on`+`sto->` does. I tried every other key and none of them seem to accidentally have that as a function. I'm not really sure what to say here other than it doesn't work for me with a fresh install of Cesium 3.4.1.

**Comment by UInt2048** [comment]
Does it work with the latest, 3.5.0?

**Comment by BruceTheShark42** [comment]
That would be a yes. I have no idea how I missed 3.5.0 when I was updating 2 days ago when it was released 18 days ago, but whatever. :P

**Comment by BruceTheShark42** [comment]
On a different note, I just realized there is a single white pixel in the bottom right corner of the screen. This screen capture was taken using CEmu, but the pixel persists in both 3.4.1 and 3.5.0 in both CEmu and on my actual TI-84+CE.
![cemu_xNyCq](https://user-images.githubusercontent.com/50778347/139660153-8ea4250b-62db-452a-8c2d-cfd59fcf212b.png)

**Comment by mateoconlechuga** [comment]
I fixed the pixel issue. It's not worth fixing the folder thing -- it doesn't even do anything.

**Comment by UInt2048** [comment]
I think they're just asking for it be consistent for all the folders, such as just always displaying the archived/locked/hidden.

**Comment by BruceTheShark42** [comment]
Actually, I take back that request. Different file types have different information associated with them. Hence the use of folders to categorize them as such.
