### ISSUE TITLE
Ability to show pictures from within Cesium

### ISSUE THREAD

**Issue by BruceTheShark42** [mateoconlechuga/cesium#201]
Hey again,

As the title states, I'd like the ability to view, not necessarily edit (although that would be pretty dang cool), pictures from within Cesium.

Ideas:
- Put them in their own folders
- Allow copying pictures to other picvars?
- A cursor that hovers over the picture, that can be moved around using the arrow keys, that shows the currently hovered color enlarged somewhere else along with it's hex representation.

**Comment by UInt2048** [comment]
There's already some cool programs for picture viewing on calculators, such as: https://github.com/TheLastMillennial/HD-Picture-Viewer

**Comment by BruceTheShark42** [comment]
In this case, I specifically meant the ability to view picvars generated by programs. For example, this:
![Pic1](https://user-images.githubusercontent.com/50778347/139734726-e1bbd291-3ba7-40f9-abe2-e31a346d0652.png)

I could just copy the picvar to my pc, convert it to a png, resize it from 265x165 to 320x240, convert it according to the  [tutorial](https://youtu.be/s1-g8oSueQg), send it back to my calculator. However the result would be stretched due to the different aspect ratios.

I could view the picvar using TIOS via `vars`+`4`, but the bottom and right sides are cropped off a little. I could also use RecallPic, but if the picvar has transparency, like the above one does, I'd have to clear the graph screen first, including disabling axes, then restore them later using a GDB or something.

The main idea behind this is workflow simplicity, and the simplest thing I can think of is to open Cesium, navigate to the picture folder, select the picvar I want to view, and then view it in its entirety without any fuss about graph settings.

**Comment by mateoconlechuga** [comment]
No.
