### ISSUE TITLE
Create "Zip" Archive [Feature request]

### ISSUE THREAD

**Issue by Unconventional10** [mateoconlechuga/cesium#202]
Add the ability to "zip" multiple files into one program for easy transfer between calculators.
One would be able to select multiple files/programs/appvars and the program would generate a single program a bit like the Cesium installer, that when run, it would generate those selected files.
I know this is pretty far-fetched, but it would be really cool.

**Comment by adriweb** [comment]
What does that have to do with Cesium though? 🤔

**Comment by Unconventional10** [comment]
This seems like something that would be easiest to implement in the cesium environment, rather than a seperate program. It would also fit in with cesium's already great file system

**Comment by adriweb** [comment]
But... Cesium doesn't have a file system, it reads the OS' "file system" (VAT).

Moreover, what you're asking seems to me like it's the existing "group" feature that the OS already offers. Check out the bottom of the Memory management menu. You can select multiple variables to be grouped, then transfer that group to another calculator for instance.
