### ISSUE TITLE
Graph Glitch

### ISSUE THREAD

**Issue by InvalidJake** [mateoconlechuga/cesium#204]
There is an issue with the graph see the video below its not too big of a problem.
https://www.youtube.com/watch?v=nyR2n7NEgTM

You switch too the graph is glitched like in the video.
![graph](https://user-images.githubusercontent.com/95587096/147160698-2b41b714-07c2-4a43-bbe4-b4efeffd5892.jpg)

**Comment by mateoconlechuga** [comment]
This has been fixed forever. Make sure you are using the latest release.

**Comment by mateoconlechuga** [comment]
fixed with c878fab
