### ISSUE TITLE
Calc freezes if plugged in and colors are inverted.

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#206]
Steps to reproduce:
Plug in calc
On the homescreen, press [on]+[sto->]
Try to press anything else.
This also occurs when uninverting the colors.

The cursor continues flashing and the colors have been inverted but it is completely unresponsive.

Tested on my 5.0.0/5.4.1 Pre-A calculator with Cesium 3.6.3.

**Comment by Bebop182** [comment]
Same bug on my TI-83 Premium CE on 5.4.0.0034 with Cesium v3.6.3

**Comment by mateoconlechuga** [comment]
Fixed and closed
