### ISSUE TITLE
Calculator crashes and resets RAM when running installer

### ISSUE THREAD

**Issue by Nanobot567** [mateoconlechuga/cesium#208]
Steps to reproduce bug:

1. Transfer cesium.8xp to calculator using TiLP2 on Linux
2. Delete Cesium application
3. Run installer for Cesium

Other information:
- My CE defragged after I deleted the Cesium app
- This happens in CEmu as well (TI-OS 5.3 and TI-OS 5.7)
- Calculator info:
     - Date code: L-0315

**Comment by adriweb** [comment]
Just so you know, the important hardware information are these: (not the regulatory information you copied, these are pretty much the same on all calcs)

![image](https://user-images.githubusercontent.com/660896/147786232-6de7a8c4-1619-418d-92a8-7c2a02883fce.png).

BTW, there's no 5.6.3 or 5.6.0 Cesium, that's the OS version. Cesium versions are visible in the app itself when you select the Cesium program, and in the [releases](https://github.com/mateoconlechuga/cesium/releases) pages.

**Comment by Nanobot567** [comment]
Ah, okay. Thanks for clearing that up :)

**Comment by mateoconlechuga** [comment]
Can you send me your ROM in CEmu? I can't reproduce otherwise.

**Comment by Nanobot567** [comment]
[Cemu.rom.txt](https://github.com/mateoconlechuga/cesium/files/7818402/Cemu.rom.txt)

Here's the ROM. (I had to upload as a .txt because of Github hating file types it doesn't   recognize. It should still work if you remove the .txt at the end)

**Comment by PeterTillema** [comment]
I can confirm this as well. It happens immediately after executing the installer. Debugging the installer shows me it crashes during `port_old.unlockhelper`. There it jumps to a `out (bc), b` and doing random stuff.

OS version 5.3.0.0037
CEmu version v1.3 (git: 87c3b43)
Cesium version: v3.6.3
I may share the ROM too if that's necessary.

**Comment by adriweb** [comment]
What's the boot version though? It's not os-based anymore.

**Comment by PeterTillema** [comment]
This is in CEmu, not sure it has a boot version?

**Comment by mateoconlechuga** [comment]
Can you email me the rom?

**Comment by LogicalJoe** [comment]
After some basic testing, I only had issues with boot 5.6.1.0006 - with every OS, it either froze or reset every time in CEmu.

**Comment by mateoconlechuga** [comment]
This is a CEmu issue, not a Cesium issue.
