### ISSUE TITLE
Restore color inversion at startup

### ISSUE THREAD

**Issue by mpi3d** [mateoconlechuga/cesium#209]
I am wondering if it is possible to add a feature to restore the last color inversion state after the screen turn back on. Without pressing `on` + `sto->` each time.

Thanks for your support.

**Comment by mateoconlechuga** [comment]
No.

**Comment by beckadamtheinventor** [comment]
Explanation:
Unfortunately this isn't possible anymore.

**Comment by mpi3d** [comment]
I see. I guess that's because TI as locked program execution on startup.

**Comment by beckadamtheinventor** [comment]
It's because they broke/removed the startup hook.

**Comment by mpi3d** [comment]
Ok, thanks for the answer.
