### ISSUE TITLE
Alpha search seems to be stuck on

### ISSUE THREAD

**Issue by 64BitUniverse** [mateoconlechuga/cesium#211]
I wanted to poke around a bit and see what the interface was like. When I wanted to quit or turn off my calculator, the [on + sto] shortcut didn't work (that is the way to close Cesium right?).

This follows into my second issue, where on commands don't seem to be working even though they are highlighted in the mode menu. I also tried to do the dark mode short cut, but all it did was move my cursor on the screen to whatever letter was associated with the key. So the [on + sto] command just moved the curser to the bottom of the screen since there's no file that starts with X and [on + ln] moved my cursor to the file that starts with S.

I looked through the closed issues and noticed that you asked for the last part of the serial last time someone has issues with the alpha stuff. Mine is L-0216C. Hope that helps.

**Comment by mateoconlechuga** [comment]
The `[on]` key shortcuts are to be used from outside Cesium, such as on the home screen where you put equations in.
