### ISSUE TITLE
Possible Python usage

### ISSUE THREAD

**Issue by Jelte2357** [mateoconlechuga/cesium#212]
Could it be possible to add the opening and edditing of python programs in the cesium shell instead off having to open python and doing that?

**Comment by adriweb** [comment]
I doubt that TI has provided a way to "deep link" inside the Python app for opening/editing a specific python script appvar. So unfortunately that seems impossible currently.

**Comment by mateoconlechuga** [comment]
No. People who use python are doing things wrong.

**Comment by adriweb** [comment]
> No. People who use python are doing things wrong.

( Well, complain to the governments who put programming (using python) in the curriculum :P Looks like it's a worldwide phenomenon though )
