### ISSUE TITLE
Invert Colors doesn’t work on Ti 84 Plus Ce Python Edition

### ISSUE THREAD

**Issue by Jeremy5909** [mateoconlechuga/cesium#213]
Dont merge this, I’ve tried holding it and doing it as soon as it starts. Nothing. I’ve updated to latest cesium and it does not work

**Comment by mateoconlechuga** [comment]
It does work trust me. You are doing something wrong.

**Comment by Jeremy5909** [comment]
Dang.
Any chance it ever will?

**Comment by Jeremy5909** [comment]
> It does work trust me. You are doing something wrong.

it doesn't work for me. Please help a little further instead of "You are doing something wrong." I don't believe I am.

**Comment by adriweb** [comment]
- Do you have the latest Cesium version from here?
- What's your datecode/hardware revision? (On the back of the calc, it's the characters like `L-0921T`.
- Does it behave the same way after resetting the calc? (Holding the reset button for like 3s)
- Does it behave the same way before and after having run the python app?

**Comment by Jeremy5909** [comment]
1. Yes
2. L-0621T
3. No, I have to launch Cesium first otherwise the on-shortcuts dont work (like on->stat still works for password)
4. Yes

**Comment by Jeremy5909** [comment]
Its been 11 days -- anyone?

**Comment by adriweb** [comment]
Well we aren't able to reproduce the issue, apparently, so... :(
