### ISSUE TITLE
Weird screen bug after installing cesium

### ISSUE THREAD

**Issue by BenBenny11** [mateoconlechuga/cesium#216]
After I installed Cesium, I opened the application, then quit it, then the calculator screen itself had some weird bug after
![issue](https://user-images.githubusercontent.com/50433844/174007631-498e843d-8036-46a0-b144-1b94ec110104.png)
.

**Comment by BenBenny11** [comment]
You might need to zoom in on the screen its a bit small

**Comment by mateoconlechuga** [comment]
I cannot reproduce with latest Cesium. What version are you using?

**Comment by mateoconlechuga** [comment]
Okay I can reproduce now :)

**Comment by mateoconlechuga** [comment]
Probably fixed with [b7eb747](https://github.com/mateoconlechuga/cesium/commit/b7eb74789d46aec816676c66c357706d5b6f1522)
