### ISSUE TITLE
Corruption in copying from flash drive

### ISSUE THREAD

**Issue by Iamaprogramador** [mateoconlechuga/cesium#217]
I think the problem is with the way Cesium handles the files from the drive, or the way it copies them over. The same programs always break the same ways. 

This is how various programs work when downloaded from the flash drive with Cesium. 
Calcuzap freezes the calc at the homescreen. 
SolitiCE works fine executed from the homescreen, but when executed in Cesium, it ram resets the calc whenever you exit Cesium. 
Banchor works fine, no problems that I can see. 
ICE fails to both detect source programs and change the program editor. 
S.A.M.M. Works fine, but since the world is so big, there could be bugs I failed to detect. 
TI boy detected a corruption in Pokémon yellow, and won’t run it. 
TI boy tries to run Space invaders, but crashes the calc and ram resets. 
1010 works fine, aside from a couple random lines of binary on the screen.

**Comment by mateoconlechuga** [comment]
I believe I have resolved this in [cab8e47](https://github.com/mateoconlechuga/cesium/commit/cab8e47ff44c2a9122aa213ccc48a0db28810bac)
