### ISSUE TITLE
Clearing the ram via "mem -> Reset -> All RAM -> Reset" still clears programs and also deletes backups

### ISSUE THREAD

**Issue by kalebchoi** [mateoconlechuga/cesium#218]
When clearing the ram via mem -> Reset -> All RAM -> Reset, all the programs still seem to get erased and so do the backups. I cannot create a backup with on +8 until I reopen cesium. and I cannot restore the backup with on +2 at all. I need to create a new backup to restore a backup with on +2.

**Comment by mateoconlechuga** [comment]
I don't think I'll plan to fix this one due to the implications it could be used for cheating.
