### ISSUE TITLE
Monochrome BASIC icons are not interpreted/displayed properly when the graphics hex string is succeeded by a double quotation mark.

### ISSUE THREAD

**Issue by NCKiser** [mateoconlechuga/cesium#222]
Monochrome 16x16 and 8x8 BASIC header icons are not displayed properly when a closing quotation mark is present (as laid out in the icon_descriptions.md file included in the release), and instead being displayed as a 16x16 color icon. For the monochrome icons to be displayed correctly, the trailing double quote mark needs to be removed.

**Comment by NCKiser** [comment]
Proposed workaround: https://github.com/mateoconlechuga/cesium/pull/221

**Comment by mateoconlechuga** [comment]
Fixed with [b7eb747](https://github.com/mateoconlechuga/cesium/commit/b7eb74789d46aec816676c66c357706d5b6f1522)
