### ISSUE TITLE
make builtin directories a cycle

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#223]
+ enable/disable stuffs for program/apps and program/apps/appvars, maybe also a toggle to disable entirely?

**Comment by mateoconlechuga** [comment]
can you just tell me exactly what to do lol

**Comment by LogicalJoe** [comment]
Put the Apps directory in Programs, put Appvars in Apps and put Programs in Appvars
Have a radio button to enable/disable the Appvar dir, and maybe one for Apps.

**Comment by adriweb** [comment]
I assume you meant Programs in Programs, not in Appvars.

**Comment by mateoconlechuga** [comment]
Added with [ba4292d](https://github.com/mateoconlechuga/cesium/commit/ba4292d0d192cceff9c6a19df7da9103161e26b7)
