### ISSUE TITLE
Cesium v3.6.4 crashing calculator and clearing RAM

### ISSUE THREAD

**Issue by BobSaidHi** [mateoconlechuga/cesium#224]
Hello,
I recently deleted my old Cesium App and App Var.  Then I installed Cesium v3.6.4 (latest) from v3.6.3 with the provided installer program.  When I ran Cesium from the apps menu, my calculator restarted and I got the RAM cleared message.

Model: TI-84 Plus CE
OS: 5.4.0.0034

**Comment by mateoconlechuga** [comment]
That's awesome. Can you provide any more information? A ROM dump using TILP would be awesome.

**Comment by adriweb** [comment]
That said, does it happen again now (after the reset)? Maybe the calc was in a weird state...?

**Comment by mateoconlechuga** [comment]
Closing as there's not enough info yet to reproduce the issue.
