### ISSUE TITLE
RAM clears when launching the Cesium app

### ISSUE THREAD

**Issue by Spaceboy10** [mateoconlechuga/cesium#227]
I just updated to the new release of Cesium with arTIfiCE, and now every time I run the app it clears my RAM.

Steps to recreate:
1. Delete the Cesium app and appvar from the previous release
2. Transfer arTIfiCE and the latest Cesium installer to the calculator
3. Run the Cesium installer through arTIfiCE and delete the installer
4. Open the Cesium app

If it helps i'm on a rev. S CE Python with OS 5.7.0.0017
![VID_20220916_203625](https://user-images.githubusercontent.com/102557131/190833542-55576c40-f7db-40ed-b6eb-5115499da1bd.gif)
EDIT: I just installed the previous release (3.6.3), and that works for some reason.

**Comment by mateoconlechuga** [comment]
Fixed in v3.6.4
