### ISSUE TITLE
Cesium doesn't run BASIC programs correctly

### ISSUE THREAD

**Issue by RoccoLoxPrograms** [mateoconlechuga/cesium#228]
On the newest version of Cesium (3.6.5), Cesium always runs whatever program is currently shown on the bottom of the screen. It only seems to do this when trying to run a BASIC program. C and ASM programs appear to run just fine. Also, if there is no program on the bottom then it just freezes and the RAM has to be reset.

**Comment by mateoconlechuga** [comment]
Fixed in 3.6.4
