### ISSUE TITLE
Custom OS error messages not being shown

### ISSUE THREAD

**Issue by calc84maniac** [mateoconlechuga/cesium#229]
This worked in very old releases, but not more recent ones. I get the feeling it's related to this code [here](https://github.com/mateoconlechuga/cesium/blob/76fd6dd8fe5594812cf08543a24ba8326753af74/src/execute.asm#L481) that is explicitly excluding custom errors for some reason.

An easy way to test this is to run the TI-Boy CE launcher without its data appvar present on the system (which is how I learned about this), or you could make a simple C program that throws a custom error.

Edit: Based on the comment, I assume this means the Stop token in a BASIC program throws a custom error. But I also notice that you set the custom error string to an empty string before running a program, so perhaps you just need to check whether the custom error string is also still empty.

**Comment by mateoconlechuga** [comment]
Fixed in 1467fae2a6a5af2eb99c395ff8cc342f3b6585e6
