### ISSUE TITLE
Improperly formatted 8x8 monochrome icon causes Cesium to crash

### ISSUE THREAD

**Issue by NinjaWeedle** [mateoconlechuga/cesium#230]
OS: 5.8.0

Viewing the icon for this program: https://ticalc.org/archives/files/fileinfo/476/47693.html causes cesium to crash followed by a ram clear.

**Comment by mateoconlechuga** [comment]
Fixed with [020157c](https://github.com/mateoconlechuga/cesium/commit/020157cc63216e12b6be09ca0e6f07d5cf36a110)
