### ISSUE TITLE
RAM Backup is modifying Archive

### ISSUE THREAD

**Issue by possiblynova** [mateoconlechuga/cesium#232]
When I use the RAM backup feature, it seems to also back up Archive memory, which is frustrating as I have lost considerable progress when resetting my calculator because Cesium will overwrite programs with the last backed up version, when the program was never in RAM, neither when I backed up or when I reset.

**Comment by mateoconlechuga** [comment]
No, this is the OS - it rebuilds the symbol table from flash and discovers whatever was archived.
