### ISSUE TITLE
Unable to screen capture Cesium

### ISSUE THREAD

**Issue by code32123** [mateoconlechuga/cesium#235]
I keep getting four smaller images. All the pixels seem to be there, but in the wrong order. Included are pictures of the TI-OS screen, then Cesium, and ce2048. Similar broken results with ChessCE and Ice.
![Capture19-1665957378344](https://user-images.githubusercontent.com/66290868/196060147-1205c12f-0c45-4ead-9b9b-71fbb7199dac.png)
![Capture11-1665957137617](https://user-images.githubusercontent.com/66290868/196059999-d84f43bd-f5aa-4f2d-bc34-132f8ea0fd34.png)
![Capture13-1665957143284](https://user-images.githubusercontent.com/66290868/196060002-5595f570-b7fc-47ca-b931-41f7c262ccbb.png)

Let me know there's any other information you need.
TI-84 Plus CE v5.4.0.0034
TI-Connect CE v5.6.0.2082

**Comment by adriweb** [comment]
Are you running it on TI's emulator ? (SmartView CE).
If so, that's why - their emulator doesn't actually correctly emulate the LCD to take into account some of the settings.

So it only works on a real calculator, or in CEmu.

**Comment by code32123** [comment]
No, I've got the real calculator - is there a revision number on the calculator somewhere that would be helpful to you?

**Comment by jacobly0** [comment]
The only way to screen capture with a real calculator is over the link protocol which also doesn't support any of the LCD settings.  There's not even enough information to know which double-buffered image is the "current" one.

**Comment by code32123** [comment]
Ok! So if I want a screenshot of a program, I need to upload the app and vars to wabbitEMU or another emulator?

**Comment by adriweb** [comment]
> No, I've got the real calculator

That's quite unexpected then. Is it behaving the same after a RAM reset? (Holding the reset button on the back for around 3s. Note that you should archive/backup anything you don't want to get deleted)

> is there a revision number on the calculator somewhere that would be helpful to you?

Yes, on the back of the calculator, you may see a serial number and possible characters like L-1234X, let us know what those are.

**Comment by jacobly0** [comment]
As mentioned, the only CE emulator that supports some of the LCD settings is [CEmu](https://github.com/CE-Programming/CEmu) which supports screenshots just fine.

**Comment by code32123** [comment]
Ok, I see L-0122W on mine. Got it a few months ago.
I'll reset the RAM here in a second and edit this

**Comment by adriweb** [comment]
Well, no need, I edged my reply as I misread your original post. It's all behaving as expected as jacobly explained!

**Comment by code32123** [comment]
Ok, understood! Thank you!
