### ISSUE TITLE
Cesium Crashes when opening notes from usb.

### ISSUE THREAD

**Issue by Log4Jake** [mateoconlechuga/cesium#238]
So I went to run Notes off my USB drive on my TI 84 plus ce python edition L-0221R 5.6.1 it first ram reseted then show a frozen screen with random Characters on it. I would reset it any it would be the same. I then took my battery out of it and put it back in and it was fine. I then tried to replicate it and my calculator would just reset twice and be fine.
[Videos](https://photos.app.goo.gl/UGmLP4n8bnub9ndj7)

**Comment by mateoconlechuga** [comment]
Notes is a compressed program that uses an older compression technique that requires the program to actually be on the calculator. Unfortunately this a problem with Notes, not with Cesium
