### ISSUE TITLE
Feature to allow AppVars to be stored in a connected USB drive

### ISSUE THREAD

**Issue by bmec2501** [mateoconlechuga/cesium#239]
I would like to store a large number of games and photos in a connected 1 tb usb drive and someone in the Cemetech discord suggested that I leave an issue here to suggest a feature that would allow Appvars to be accessed on the same usb drive as the main program. Thanks

https://discord.com/channels/466808269789200384/466819249063854090/1040447737965068339

**Comment by mateoconlechuga** [comment]
This is literally impossible.

**Comment by fghsgh** [comment]
It is not impossible if you require the user to tell Cesium ahead of time which appvars it has to load at the same time as the program. This can be a one-time effort, or Cesium could even detect new appvars after regaining control when the program exits and add them to the list automatically. Copying what I said on Discord:

> it doesn't have to be seamless and just figure out itself which programs to load
> it could either 1. load everything in the directory, 2. have extra metadata for knowing what files from the directory to load (like an extra hidden file, or not hidden file)
> or you could do the apple-inspired thing that directories that end in .app can be launched (which would load everything inside it and run the program with the same name as itself)
> all of this would require some amount of effort from the user to tell it what to load, but it's a one-time effort 
> and after the program is finished running it could store all the appvars/programs that were modified back, but it's probably needed to also keep track of newly created variables
> but none of that is impossible

> imagine this for a sec
> here is a folder on the flash drive called program.8xx
> if the user presses enter on it, the shell automatically loads everything in the directory onto the calc, stores a list of all programs and appvars to its own appvar, and launches prgmPROGRAM
> when that exits it goes through the list it made and if there were any new additions, stores them to the directory; it also goes through everything that was in the directory and compares it against what is on the calc, if there is a difference it updates the version on the drive 
> alternatively, replace directory with plaintext file that lists files
> and the "keeping track of a list of all existing programs and appvars" is optional, you could just say that's the user's responsibility to figure out

A better name for this feature would be "ability to set up presets of variables to load from USB simultaneously with a program".
