### ISSUE TITLE
Tune the Clock in Cesium

### ISSUE THREAD

**Issue by ValkTheBoxman** [mateoconlechuga/cesium#240]
At the time of writing this issue, for me its 9:53 AM while my 84 plus CE-T Python edition displays 6:15 pm

How do i retune it?

**Comment by adriweb** [comment]
At the Home Screen (not in cesium), press [mode] then at the bottom there are the clock settings.

**Comment by ValkTheBoxman** [comment]
ok, thanks i got it :)
