### ISSUE TITLE
Disables/changes the AppChange hook without restoring

### ISSUE THREAD

**Issue by LogicalJoe** [mateoconlechuga/cesium#241]
On running the application (and running an application, among other things), Cesium will disable the AppChange hook.  When editing a program the hook is used but not restored (which doesn't matter because the flag is zeroed anyway).  This breaks some of TI's app functionality, shown below is Transformation Graphing's [Format] menu, which is reset to the default menu when Cesium is entered/exited because the appchange hook is uninstalled, this is not the only thing it handles for this app but is one of the most obvious.
![Transformation-Appchangehook-disabled](https://user-images.githubusercontent.com/47825483/210123019-8e96d06b-c346-4890-8bd6-3ea1eccb0eb7.png)

**Comment by mateoconlechuga** [comment]
fixed in [9b47151](https://github.com/mateoconlechuga/cesium/commit/9b471519eed83fdd4fb1b45271096ee434601be2)
