### ISSUE TITLE
Pressing "clear" resets RAM / How to exit Cesium shell / "on" shortcuts don't work

### ISSUE THREAD

**Issue by woubulbus** [mateoconlechuga/cesium#242]
I have a TI-84 Plus CE on OS 5.3.0.0037 with Cesium 3.6.4 installed. The latest version of clibs is installed (if it matters). 

Cesium opens, launches apps, works normally, etc.

There is no key bind to exit Cesium so I presume its the clear button?
Pressing the clear button resets memory and I'm not sure if it's supposed to do that.
Once I'm back at the home calculator screen, pressing "on + prgm" or any other "on + [key]" doesn't do anything. ("Enable [ON] key shortcuts" is on).

It looks like there is another issue report saying that "Backup RAM" causes these issues and it looks like that's the case for me, only except the issue is closed. 

If any more detail is required, let me know.

**Comment by mateoconlechuga** [comment]
Perform a full reset of your calculator and then try.

**Comment by MaristokGithub** [comment]
Nah man, who wants to do a full reset? Try [2nd] then press the [mode] button.
