### ISSUE TITLE
Visual bug when powering off while in program editor

### ISSUE THREAD

**Issue by HolographicSludge** [mateoconlechuga/cesium#243]
When the calculator is turned off normally (without password on wake) while the user is editing a program through Cesium, turning it back on will display a consistent static-like pattern on the home screen until you press clear. If you power down with password on wake instead, the glitch appears for a few frames while the calculator is shutting down but not after it’s turned back on.

As far as I can tell the only setting that affects this bug is mathprint mode, which causes only the top few pixels of the "static" to appear when the glitch is performed, as shown in the 2nd screen capture below (the 1st is what appears in classic mode). I believe this may be similar to #216, though the pattern seems a bit different.

![classic](https://user-images.githubusercontent.com/131316370/233225850-298e21dd-1dfc-4a6d-aefd-b91446bf2ca4.png) ![mathprint](https://user-images.githubusercontent.com/131316370/233225888-d72abc93-6bc6-487f-b6ab-c86b116323de.png)

**Comment by 0x5b62656e5d** [comment]
The visual glitch can also be produced this way:
1. Launch Cesium
2. Go to apps folder and open CellSheet
3. Press any key to continue then go to menu
4. Quit CellSheet

It happens 100% of the time with CellSheet and only sometimes with other apps. It also happens with Periodic and Inequalz.

**Comment by mateoconlechuga** [comment]
fixed in [9b47151](https://github.com/mateoconlechuga/cesium/commit/9b471519eed83fdd4fb1b45271096ee434601be2)
