### ISSUE TITLE
Calculator not using the vars in USB Drive

### ISSUE THREAD

**Issue by FlyAvalan** [mateoconlechuga/cesium#244]
Hello, when I run apps that uses AppVars, the app can't seem to find them in my USB drive? Is there a way to sort of trick the app into thinking it is inside the calculator main drive so I can run programs on the USB drive completely?

**Comment by mateoconlechuga** [comment]
No there is not. I have considered creating a file that tells Cesium what files in a directory to load as well, sort of like a package, but no one has really put too much thought into how it should work so for now nothing exists.

**Comment by FlyAvalan** [comment]
> No there is not. I have considered creating a file that tells Cesium what files in a directory to load as well, sort of like a package, but no one has really put too much thought into how it should work so for now nothing exists.

Alright thanks 👍
