### ISSUE TITLE
On-shortcuts deactivate when opening Inequalz y= menu

### ISSUE THREAD

**Issue by rhysdh540** [mateoconlechuga/cesium#246]
when opening the inequalz app and then going to the y= (or x=) menu, cesium's on-shortcuts (on+prgm, on+stat, etc) stop working until cesium is reopened from the apps menu.

**Comment by LogicalJoe** [comment]
iirc Inequalz (and other apps) overwrite hooks and never restore or chain them, only way to fix this would be to reinstall the hook using a different hook that is not overwritten afterwards.

**Comment by mateoconlechuga** [comment]
Not worth fixing just reopen Cesium
