### ISSUE TITLE
Add feature for managing groups

### ISSUE THREAD

**Issue by CommentedNewline** [mateoconlechuga/cesium#247]
It would be nice if Cesium had a group creator/ungrouper

**Comment by CommentedNewline** [comment]
But it is hard to get all the stuff you want with it without scrolling through a hundred pages of junk.
For example, if I wanted to get, let's say, five APPVARS and three programs, the only way to do that is to go through the ALL- menu which takes forever. What I'm thinking is being able to select any file you want using, say, a checkbox.
<p font-size:2pt>I'm not mad. just suggesting stuff</p>

**Comment by CommentedNewline** [comment]
Years Later, @CommentedNewline has come to his senses.

**Comment by mateoconlechuga** [comment]
?

**Comment by CommentedNewline** [comment]
I realized that this feature isn't that practical.
I won't close it, though, but you can.
