### ISSUE TITLE
Crinkling at top of screen when closing a program

### ISSUE THREAD

**Issue by THEESMARTONE** [mateoconlechuga/cesium#248]
When I exit a program on my ti 84 plus ce with cesium there is a weird black-and-white insert that comes at the top of the screen. I use clear to clear it out, but it's annoying. Is there any way to fix this? I will provide photos if needed.

**Comment by mateoconlechuga** [comment]
What program are you running that causes this?

**Comment by THEESMARTONE** [comment]
Dear Matt,

It's when I use the base TI apps. Some of them don't give it and others do.

*Sincerely, *
*Srishtijit Bhadra*
*Class of 2027*
"*The greatest glory in living lies not in never falling, but in rising
every time we fall." -Nelson Mandela*

**Comment by mateoconlechuga** [comment]
fixed in [9b47151](https://github.com/mateoconlechuga/cesium/commit/9b471519eed83fdd4fb1b45271096ee434601be2)
