### ISSUE TITLE
Certain programs do not want to work

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#250]
This program that I have downloaded gives an invalid error when used
https://www.cemetech.net/downloads/files/1751/x1751
All files are downloaded and the proper program is used.

**Comment by Potato-Man1234** [comment]
Running on OS 5.8.0.0022

**Comment by mateoconlechuga** [comment]
Are you running from the home screen or from Cesium?

**Comment by Potato-Man1234** [comment]
Cesium

**Comment by mateoconlechuga** [comment]
This is an issue with program, not with Cesium. You will have better luck reaching out to the author of the program

**Comment by Potato-Man1234** [comment]
Ok, Thank you
