### ISSUE TITLE
Better control over brightness settings?

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#252]
The setting for brightness could be improved upon:
-Show a numeric for brightness (the higher brightness levels are very hard to distinguish from each other.)
-Override the brightness buttons on the calculator, if possible. To allow the full range to be chosen from without snooping through the Cesium settings.

**Comment by mateoconlechuga** [comment]
added in [78fa2eb](https://github.com/mateoconlechuga/cesium/commit/78fa2eb9940dc666adbcf6ff9cbcb9bd6f510ed0)
I will not be overriding the brightness buttons
