### ISSUE TITLE
Cabri Jr V5.0.0.0089 is Broken after using cesium

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#253]
Steps:
-open Cabri Jr either through Cesium or without it
Cursor does not move
attempting to draw causes Cabri Jr to freeze
looks like #243 once it is force reset

**Comment by Potato-Man1234** [comment]
Have not been able to reproduce it after shutting the calculator down.

**Comment by Potato-Man1234** [comment]
![Capture3-1695488080176](https://github.com/mateoconlechuga/cesium/assets/145854899/9681e79a-e733-443c-8c1e-6decf6f37225)
![Capture2-1695488087841](https://github.com/mateoconlechuga/cesium/assets/145854899/6b585f61-dee3-4a75-828a-3bf410440856)

**Comment by Potato-Man1234** [comment]
Might be very serious
![Capture4-1695488200075](https://github.com/mateoconlechuga/cesium/assets/145854899/1ca27d8d-e5e5-4c2d-bbc2-3b432fec579d)

**Comment by mateoconlechuga** [comment]
fixed in [9b47151](https://github.com/mateoconlechuga/cesium/commit/9b471519eed83fdd4fb1b45271096ee434601be2)
