### ISSUE TITLE
Add compatibility with Doors CSE programs or make a TI-Basic icon editor

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#256]
The program that was highlighted to be used for making TI-Basic icons and descriptions in icons_descriptions.md is not compatible with the current release of Cesium and requires Doors to be used,  is there a work around that can be done?

**Comment by mateoconlechuga** [comment]
Can you please be more specific? The highlighted program works fine for creating icons.

**Comment by Potato-Man1234** [comment]
When I run the program it tells me to download Doors CSE to run it,  isn't that another shell?
![Capture4-1695682849731](https://github.com/mateoconlechuga/cesium/assets/145854899/e56c9afe-82fb-4dc1-8a7b-7c661c051e88)

**Comment by mateoconlechuga** [comment]
Huh they must have updated the program and the link is no longer relevant. Thanks!

**Comment by Potato-Man1234** [comment]
Found the older version
[https://www.ticalc.org/archives/files/fileinfo/455/45564.html](https://www.ticalc.org/archives/files/fileinfo/455/45564.html)

**Comment by mateoconlechuga** [comment]
Closed with [8e0eaa6](https://github.com/mateoconlechuga/cesium/commit/8e0eaa6b640c449350a396afbe224512b659504a)
