### ISSUE TITLE
Lowercase alpha no longer showing up?

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#257]
Did the last instance of Cesium have lowercase alpha characters?  For some reason they are missing now.

**Comment by mateoconlechuga** [comment]
Can you please try to describe your issues in more detail and how to reproduce them.

**Comment by Potato-Man1234** [comment]
Press Alpha twice,  the lowercase form no longer shows up,  I just downloaded yesterdays release and noticed they were missing when I was making a basic description.

**Comment by mateoconlechuga** [comment]
Where do I press alpha twice.

**Comment by Potato-Man1234** [comment]
I was stupid again! That was ICE compiler, sorry for wasting your time.
