### ISSUE TITLE
Add user folders

### ISSUE THREAD

**Issue by juniorRubyist** [mateoconlechuga/cesium#26]
It would be nice if we could sort our programs into folders.

**Comment by LAX18** [comment]
It would be...

**Comment by jcgter777** [comment]
Not happening.

**Comment by adriweb** [comment]
User folders have previously (calcs older than the CEs) been done using a byte in the var format that was unused. TI now uses it on the CE, thus making it impossible (that way).
I'll close that but in case @mateoconlechuga ever wants to do it in a different way, he'll probably reply and refer to it in a commit :P

**Comment by LAX18** [comment]
I figured as much... I hope to add something similar on my shell but we will see how that goes.

**Comment by jcgter777** [comment]
I've asked Mateo already a long time ago, and he said he'll never add them.
