### ISSUE TITLE
Painfully slow when ROM is filled with tiny files

### ISSUE THREAD

**Issue by ditistijn** [mateoconlechuga/cesium#260]
To use the new HDPICV zoom functionality you need to export the image in 100 separate files. After loading 1500 files onto the calculator Cesium just gets painfully slow while opening it.

**Comment by adriweb** [comment]
I very much doubt the calc (OS or Cesium) was design with such a crazy usecase in mind. You should probably just... not do that.

**Comment by ditistijn** [comment]
That does make sense although I wonder what other piece of software there
is that lets me do this without that much tiny images

**Comment by mateoconlechuga** [comment]
this is more of an issue with the software being used - the calculator wasn't really intended to handle that many files. Closing for now :(
