### ISSUE TITLE
Visual glitch in archived editor

### ISSUE THREAD

**Issue by Potato-Man1234** [mateoconlechuga/cesium#262]
Steps to reproduce:
1)Have the same program on your calculator and TI Connect CE
2)Archive said program
3)Use Cesium to edit the program while archived
4)Use TI Connect CE to send the program un-archived to the calculator
5)The home screen should pop up an look like this:
![IMG_0475](https://github.com/mateoconlechuga/cesium/assets/145854899/673ef2cc-6e48-4e1c-b4e3-93452157a33a)
TI Connect CE does not see the glitch and only sees what the calculator is supposed to look like.

**Comment by mateoconlechuga** [comment]
Not supported behavior
