### ISSUE TITLE
restoring ram from back up, causes calculator to crash

### ISSUE THREAD

**Issue by dan9936054** [mateoconlechuga/cesium#263]
restoring ram from back up with cesium 3.6.7 on a TI-84 Plus CE python 5.6.1.0012 causes calculator to crash 
steps to reproduce issue:
press on+8
press on+2

**Comment by FurriousFox** [comment]
same issue on 5.8.0.0022

**Comment by mateoconlechuga** [comment]
Can't reproduce. What is the behavior you expect to see?

**Comment by FurriousFox** [comment]
yes, the equation is still there, but

For example, input the equation Y1=7*7

press on+8
change the equation to Y1=10*10
press on+2

the equation is still Y1=10*10 instead of the expected Y1=7*7
like, it doesn't manage to accidentally reset ram, but it doesn't restore any ram either

**Comment by dan9936054** [comment]
> Can't reproduce. What is the behavior you expect to see?
> 
> For example, input the equation Y1=7*7
> 
> press on+8 press on+2
> 
> The equation is still there, no?

no, the equation is gone along with the time and everything else in ram.

**Comment by mateoconlechuga** [comment]
@FurriousFox sounds like you aren't actually using the backup feature. Do you see the the text "Backup up" in the status bar, and does the calculator power cycle?

@dan9936054 The time and brightness levels are not stored in RAM. Hence they cannot be "backed up"

**Comment by FurriousFox** [comment]
I'm using the backup feature, I've added a video below showing the issue in action

https://github.com/mateoconlechuga/cesium/assets/49615248/8226fb1d-e6d3-4e02-8227-8b670aa76f70

**Comment by dan9936054** [comment]
> I'm using the backup feature, I've added a video below showing the issue in action
> 
>  MP4_20231212_190232.mp4

that’s exactly what it looks like for me

**Comment by dan9936054** [comment]
> @FurriousFox sounds like you aren't actually using the backup feature. Do you see the the text "Backup up" in the status bar, and does the calculator power cycle?
> 
> @dan9936054 The time and brightness levels are not stored in RAM. Hence they cannot be "backed up"

sorry for my ignorance as I assumed they would be stored in ram, or at least I assumed they wouldn’t be reset when restoring a ram backup…
