### ISSUE TITLE
Ability to create folders and/or place programs in a selected order

### ISSUE THREAD

**Issue by njphill0119** [mateoconlechuga/cesium#268]
As the title says, I want to be able to have more organizational control over programs. I'm a little new to this so I'm not sure if this is actually possible, but thought it could make a neat addition to this already great app.

**Comment by LogicalJoe** [comment]
#26 #135 #142

**Comment by njphill0119** [comment]
> #26 #135 #142

Thank you, I didn't think to look through those. I'll close this one down!
