### ISSUE TITLE
Password system has too easy of a reset mechanism.

### ISSUE THREAD

**Issue by zephr1213** [mateoconlechuga/cesium#275]
I'm not too sure how Ti-84 OS works, but if there is any way to not have the password be disabled when you click the reset button on the back, that would be amazing. Not sure if that's possible though. I am suggesting a mechanism like the test feature built in to the ti84 that is disabled by sending something to the calculator. Just a suggestion.

**Comment by LogicalJoe** [comment]
#145 among others
