### ISSUE TITLE
More detailed tutorial on how to get USB working, and how to copy between?

### ISSUE THREAD

**Issue by FunnyHotDog** [mateoconlechuga/cesium#277]
So I am mostly meaning: do I need a usb micro b to female usb a, or just find somehow a micro-b connector flash drive?

**Comment by Aquateraneal** [comment]
I use an adapter, you can find them on Amazon with a bit of work.
I don't know if there are mini-B flash drives out there.
(I'm pretty sure it's **mini**-B, not micro-B)

**Comment by FunnyHotDog** [comment]
ok thanks!
