### ISSUE TITLE
Failure to run PrgmA

### ISSUE THREAD

**Issue by Xanjaxn** [MateoConLechuga/Cesium#3]
Whenever I run **PrgmA**, the error screen comes up with the message: *Attempted to use a function or variable where it is not valid.* When I run **PrgmCesium**, it just says Done. Any advice?

**Comment by adriweb** [comment]
A bit more info is needed:
- What OS version is your calculator running? (`2nd`,`+`,`Enter`). Version 5.1.5 is recommended.
- What Hardware Revision is your calculator (Look at the back of the calc, there should be a few characters next to the serial number, like "L-0515**B**")
- Have you downloaded the _latest_ Cesium version? ([here](https://github.com/MateoConLechuga/Cesium/releases/latest))
- Were you running any other ASM program beforehand, especially hooks (like PHASM, etc.)

`prgmA` should be the only one needed to be run, btw.

**Comment by Xanjaxn** [comment]
**OS:** 5.0.1.0012 (TI-Connect said I had the most recent update)
**Hardware Revision:** L-0715A
I just reset all memory and used the most recent Cesium version, but I get the same error message. And no, all I have is Cesium running.

**Comment by adriweb** [comment]
Hmm, it's a bit weird it does that, but I'm going to recommend updating to the latest CE OS, because 5.0.1 is definitely not the latest :)
You can find it [here for the 84+CE](https://education.ti.com/en/us/software/details/en/158B7669E4C0493A84D33D9A22FDBD3C/ti-84plusceoperatingsystem), and [here for the 83 Premium CE](https://education.ti.com/fr/france/software/details/fr/B1B863F270AB4381A836C38E88A94127/ti-83-premium-ce-operating-system).
Let us know how that goes once updated.

**Comment by Xanjaxn** [comment]
I tried that earlier, but how to I update with the .8eu file?

**Comment by adriweb** [comment]
Drag'n'Drop it on your calc, in TI-Connect CE (calculator explorer "tab", I think)

**Comment by Xanjaxn** [comment]
The TI-Connect program has a OS downloader tool, but it doesn't have the TI-84 Plus CE as an option, only Silver edition and C Silver Edition. Also, my calculator is automatically recognized as the Silver edition, so it says the .8eu is incompatible.

**Comment by adriweb** [comment]
You need to use [TI-Connect CE](https://education.ti.com/en/us/products/computer_software/connectivity-software/ti-connect-ce-software/tabs/overview), not TI-Connect ;)

**Comment by Xanjaxn** [comment]
I'm so stupid, everything is working now, I guess not everything transferred using TI-Connect.
