### ISSUE TITLE
Can't view result of computation

### ISSUE THREAD

**Issue by danielzfranklin** [mateoconlechuga/cesium#30]
If a program displays and then exits, cesium immediately returns to the cesium shell. An option to run a program and then wait for a keypress before returning so I can see the output would be useful.

**Comment by jcgter777** [comment]
I agree, but not for all programs. This is only for some BASIC programs, but there should be some detection mechanism that can tell if it displays anything, or it could add a Pause to the end. Or, you could add it yourself.

**Comment by danielzfranklin** [comment]
In terms of interoperability, it would be much easier if it was automatic. Can it be an option, just like archived, on the right hand panel?
________________________________

**Comment by mateoconlechuga** [comment]
The program has finished executing by the point the calculation is complete. There is no way to detect if a program is in this state
