### ISSUE TITLE
Cesium doesn't understand the Alpha-F5-8 'Execute Program' feature

### ISSUE THREAD

**Issue by onlymx13** [mateoconlechuga/cesium#31]
When in a program, using the built-in edit menu to run the program simply quits to the Cesium launcher.

**Comment by jcgter777** [comment]
Soooo, what's your point. It's known to do that.

**Comment by onlymx13** [comment]
That menu should run the program directly.

**Comment by mateoconlechuga** [comment]
Can't fix because TI weirdness
