### ISSUE TITLE
Cesium glitch

### ISSUE THREAD

**Issue by JasonTheKitten** [mateoconlechuga/cesium#32]
If you archive the apps folder, it will mess up your calculator's screen res until you reboot

**Comment by onlymx13** [comment]
This is because this abruptly exits Cesium without leaving 8bpp mode.

**Comment by jcgter777** [comment]
You should close this issue. It's kinda irrelevant.

**Comment by JasonTheKitten** [comment]
Perhaps we should, like, disable archiving the apps folder

**Comment by mateoconlechuga** [comment]
I think I fixed this in the pre-release

**Comment by JasonTheKitten** [comment]
Ok
