### ISSUE TITLE
Cesium Rewrite

### ISSUE THREAD

**Issue by mateoconlechuga** [mateoconlechuga/cesium#33]
Cesium should be rewritten:

- Fasmg support would clean up with macros and useful app-inc support
- The repo has become a hodgepodge of jerry-rigged features; they should be cleaned up and actually make sense
- There needs to be better support for a lot of feature integration of appvar handiling, usb communication, etc

**Comment by runer112** [comment]
jury-rigged*

**Comment by mateoconlechuga** [comment]
Duplicate of #34
