### ISSUE TITLE
In the rewrite, make Cesium cooler

### ISSUE THREAD

**Issue by jcgter777** [mateoconlechuga/cesium#34]
More graphical things, examples below:

- Make a loading bar (circular) for a few seconds for loading Cesium, and maybe backing up
- The backing up thing mentioned above
- Add color palette that pops up when selecting colors
- Make program icons on the left slightly bigger
- Maybe add a scrolling bar

I will add more when I remember stuff. I'll also review the post I made on the thread because there was a compiled list there.

**Comment by runer112** [comment]
A loading bar/icon seems a bit unnecessary. If anything takes longer than a second or two, the solution should be to optimize that thing, not slap a loading bar on it.

**Comment by mateoconlechuga** [comment]
Yeah but I can't really optimize this:

https://github.com/mateoconlechuga/cesium/blob/master/src/routines/loader.asm#L235

That _WriteFlash call is going to take forever.

**Comment by jcgter777** [comment]
Copied from my post in Cesium thread, and only slightly modified (Refer to them as numbers?): 
1. maybe be able to move programs around/reorder  
2. since you're adding things, why not a scrollbar... ￼  
3. (I mentioned settings whatever but...) Changing highlighting color  
4. an about page, accessed through settings  
5. more visible highlighting in the settings menu  
6. perhaps not allow a completely white icon?  
7. be able to create a group from Cesium  
8. make a backup stored in a different appvar that can be "recalled" at any time  
9. when resetting with backup on (while in a program), not reset the time  
10. maybe put clibs into Cesium so appvar list won't be as cluttered  
11. Starring programs/apps feature  
12. Maybe more folders (Think not, maybe for the rewrite if possible?)  
13. Appvar list (and hiding them) 
14. Pinning programs (to the top_ 
15. A pop up color palette when choosing colors  
16. More customizable theme like FG and BG, rainbow theme, etc. (Custom themes) 
17. Be able to change brightness in the settings menu (basically just more settings things)  
18. be able to turn off error goto (settings toggle)  
19. Eliminate 255 white as a BG color selection unless you can change text color 
20. Maybe delete the execute program menu item in the F5 menu in the Cesium editor?  
21. Have the left arrow when renaming programs and creating new programs not delete everything  
22. Have a window pop up when you want to rename/create new program

**Comment by mateoconlechuga** [comment]
1. too intensive
2. not a scrollbar but an indicator
3. okay
4. okay
5. it's fine
6. too restrictive
7. okay
8. impossible
9. impossible
10. no
11. i'll think about it
12. perhaps
13. yes, no hiding
14. no
15. done
16. done
17. okay
18. okay
19. no
20. i'll fix the underlying bug
21. no
22. no

Sorry; I still want to try and keep things lightweight. Hopefully I'm at least doing the important ones

**Comment by jcgter777** [comment]
Woot that's good
