### ISSUE TITLE
Mem errors will loop in Cesium

### ISSUE THREAD

**Issue by jcgter777** [mateoconlechuga/cesium#35]
When there's a memory insufficient error, you can't exit it. When you turn off your calc, it won't turn back on. You have to reset to fix, and even if you ran with backup, it's going to be a legit RAM clear.

**Comment by mateoconlechuga** [comment]
Could you maybe make a program in basic to reproduce this? Maybe something that fills all of memory?

**Comment by jcgter777** [comment]
I'll try to in CEmu. Would that work?

**Comment by mateoconlechuga** [comment]
Yes

**Comment by jcgter777** [comment]
I can't reproduce loop. Only with Bounce.

**Comment by mateoconlechuga** [comment]
Bounce crashes on the homescreen for me. It needs to be repaired at some point.

**Comment by jcgter777** [comment]
@mateoconlechuga You should reopen this
I was able to reproduce with AgarioCE. I just kept purposely killing myself for like 20 times, and the same loop resulted.

**Comment by jcgter777** [comment]
Just to clarify: What part of the bug is fixed in the rewrite? The mem error loop, or just Bounce's stuff. And is Agario's problem the same or different?

**Comment by LAX18** [comment]
I would like to reopen this, but for a different reason

For me, when enabling Backup RAM before executing programs, When my RAM resets and the calc turns on, I get a loop of memory errors. They prevent me from turning off the calc, or doing anything. I need to reset to fix.

**Comment by mateoconlechuga** [comment]
I am going to need a way to reproduce that. Never seen it before.

**Comment by LAX18** [comment]
1. Write a buggy ICE program (i.e write to an open slot.
2. Enable Cesium RAM backup
3. Run the said program
4. Error should occur when calc turns on


It could be my calc, but this causes it. The error occurs sometimes, but often enough that I do not use this.

**Comment by mateoconlechuga** [comment]
Can you give me the buggy ice program?

**Comment by jcgter777** [comment]
Hey @LAX18  can you replicate it on CEmu? If you can, just record it.

**Comment by jcgter777** [comment]
After trying to run programs on NOS a few times from Cesium, mem error loop happened.

**Comment by mateoconlechuga** [comment]
Can't you just post a CEmu state or something

**Comment by jcgter777** [comment]
it happened on calc, and it hasn't happened again

**Comment by mateoconlechuga** [comment]
I think my latest commit should fix this.

**Comment by jcgter777** [comment]
yay finally
