### ISSUE TITLE
Old bugs copied over, tell me if they’ve been fixed

### ISSUE THREAD

**Issue by jcgter777** [mateoconlechuga/cesium#38]
1. When running cclock by critor and Kerm, error at If "G!=1:Radian" (doesn't happen on homescreen)  
2. stick hero freezes in Cesium (not on homescreen)  
3. Phasm is stuck offline in Cesium (not on homescreen) 
4. After using ICE's trace menu in the editor, program name reappears.  
5. Sometimes, DefineSprite doesn't replace minY (only in Cesium editor) (probably fixed, I don’t remember) 

(Copied directly from thread post and I was weird back then so this may be cringy (it is, actually))

**Comment by mateoconlechuga** [comment]
1. fixed
2. fixed
3. not my bug
4. not my bug
5. fixed

**Comment by jcgter777** [comment]
YASSS
