### ISSUE TITLE
Question: Fasmg information in the readme

### ISSUE THREAD

**Issue by onlymx13** [mateoconlechuga/cesium#48]
I downloaded fasmg from the link in the readme, not just the normal flat installer. However, nothing happens when I run the exe. I guess that this is because there was something I didn't do. That information should be in the readme if that is the case.

**Comment by mateoconlechuga** [comment]
It is in the readme under 'Building'

**Comment by onlymx13** [comment]
I looked there. I clicked the link, downloaded fasmg, and extracted. Running the exe did nothing. What am I doing wrong?

**Comment by mateoconlechuga** [comment]
You run it from the console with the command in the readme. Be sure you cloned the repo correctly too

**Comment by onlymx13** [comment]
It says ez80.inc is missing

**Comment by mateoconlechuga** [comment]
The readme describes how you are supposed to clone the repo. Did you do that step?

**Comment by onlymx13** [comment]
Yes

**Comment by mateoconlechuga** [comment]
So you used the --recursive flag?

**Comment by mateoconlechuga** [comment]
![image](https://user-images.githubusercontent.com/9890252/42736388-4d09a0d2-8823-11e8-9f21-32fd92a13d25.png)

**Comment by onlymx13** [comment]
I'll redo it just to be safe.

**Comment by onlymx13** [comment]
It worked! Thanks for your help!

**Comment by mateoconlechuga** [comment]
If you cloned the repository like normal you can also just run:

    git submodule update --init

To do the same thing too. Best of luck!
