### ISSUE TITLE
Cesium uses up 10k RAM each time it runs a program

### ISSUE THREAD

**Issue by TheMadCoder1** [MateoConLechuga/Cesium#5]
I have all my programs sitting in archive except for Cesium and Prgm A, to run the shell. I thought it was great, as I could save a ton of RAM by archiving everything. However, Cesium seems to harm more than help. Each time I run a program, 10 kilobytes more are mysteriously taken up. This only happens when running with Cesium, whether the program being run is archived or not. When I run it myself, using ASM (I only tested an Assembly program) there is no RAM being lost. The only way to fix this without losing Cesium is to archive Cesium and Prgm A and do a manual RAM clear. Why is this happening? It is taking away the point of using Cesium for me. I am using a TI-84 Plus CE.

**Comment by Eeems** [comment]
which version of Cesium are you running? I just tested with 1.1.2 and did not experience this behavior

**Comment by MateoConLechuga** [comment]
This is an old issue that has been fixed for quite some time. You should update
