### ISSUE TITLE
Cesium is laggy on physical calc

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#56]
Unlike Cesium 2.5.0, Cesium 3.0.0 and 3.0.1 has a slight delay when doing anything. Running the app, running a program through Cesium, entering the settings screen, everything has a delay of about .7 seconds. This has been an issue ever since I installed the app, I don't believe any settings I have are affecting it. I can not reproduce on CEmu; only on my physical CE.

**Comment by onlymx13** [comment]
I have the same issue.

**Comment by jcgter777** [comment]
I think it's just slower when scrolling.

**Comment by LAX18** [comment]
I can also agree that I have the same issue. I especially notice a delay when exiting from the settings menu.

**Comment by jcgter777** [comment]
I think it's better.

**Comment by TheLastMillennial** [comment]
Launching Cesium is still just as slow for me, but other than that everything is much better!

**Comment by mateoconlechuga** [comment]
How many programs do you have @TheLastMillennial

**Comment by TheLastMillennial** [comment]
108
(Shared this on Cemetech but may as well share it here.)

**Comment by jcgter777** [comment]
Heh I only have 17 now.

**Comment by mateoconlechuga** [comment]
Okay I think I've somewhat fixed startup time so I'm just going to close this issue for now and then push all the changes later
