### ISSUE TITLE
Password protection doesn't work.

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#58]
When you press [on]+[stat] the calculator turns off like it's suppose to. But when you turn it back on, the password entry prompt flashes on, then just goes away after a split second.

**Comment by jcgter777** [comment]
Yah. I thought it was just me. Guess not.

**Comment by TheLastMillennial** [comment]
Oh I am an idiot. I guess you need to set a password before it works now don't you. I just assumed it would be set to the default password like previous versions. Ah well, it works now.
