### ISSUE TITLE
Pressing [2nd] + [Quit] during TIBASIC Input causes RAM reset

### ISSUE THREAD

**Issue by LAX18** [mateoconlechuga/cesium#65]
I presume this is a bug, however my calc has been behaving odd for a bit. I have done this twice now with Orbit84 and hve this happen.

**Comment by jcgter777** [comment]
Doesn't happen to me.

**Comment by LAX18** [comment]
Could be my messed up calculator

**Comment by jcgter777** [comment]
I think it's the program. My calc was messed up, but I deleted every single thing off of it and reinstalled everything.

**Comment by LAX18** [comment]
I am gonna go a OS reinstall

**Comment by mateoconlechuga** [comment]
Can't reproduce this

**Comment by jcgter777** [comment]
See LAX18?
