### ISSUE TITLE
APD is not disabled in programs.

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#68]
When running any program through Cesium, the APD is not disabled and therefor the calculator will fall asleep in the middle of executing a program. APD performs normally when programs are run outside of Cesium.
This is with Cesium 3.0.2.

**Comment by mateoconlechuga** [comment]
Then you will complain that apd leaves your programs running, and drains your battery.

**Comment by TheLastMillennial** [comment]
I'd rather my battery drain than my programs crash because my calculator fell asleep. ;)
Didn't older versions of Cesium disable APD in Cesium but not when programs were run outside of it?

**Comment by jcgter777** [comment]
This still happens in certain programs. I don't remember which one, but I'll say if I find out. reopen?
