### ISSUE TITLE
v.3.0.3 - APD is not disabled in Cesium

### ISSUE THREAD

**Issue by LAX18** [mateoconlechuga/cesium#69]
Well, I mean when running Cesium the APD is disabled and the OS shuts the screen off and causes issues.

**Comment by LAX18** [comment]
Well, I mean when running Cesium the APD is disabled and the OS shuts the screen off and causes issues.

**Comment by TheLastMillennial** [comment]
This is suppose to be fixed with the latest release. (3.0.3)

**Comment by LAX18** [comment]
It is for in programs. For in the Cesium app, OS APD works (not a good thing)

**Comment by mateoconlechuga** [comment]
Huh. Guess I'll have to fix this

**Comment by jcgter777** [comment]
Ehh this still happens. DCS9IC is the one it happens in.

**Comment by jcgter777** [comment]
@mateoconlechuga This still happens in basic programs

**Comment by mateoconlechuga** [comment]
If I disable APD, the `Pause` and `Wait` commands will no longer work. This is why it doesn't make sense to disable it for basic programs.
