### ISSUE TITLE
KryptonIDE not being set as default editor.

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#70]
I have Cesium 3.0.3 and KryptonIDE beta 16. After I updated from Cesium 3.0.2, KryptonIDE doesn't launch when I press [zoom] to edit a program; it just brings up the standard TI editor. 
I tried launching KryptonIDE  to see if it needed to install itself, but it had no effect.

**Comment by LAX18** [comment]
See my cemetech post. It has the solution there.

**Comment by TheLastMillennial** [comment]
Press [trace] to enter the program editor.
Or re-read the freaking ReadMe unlike me. :-P
(Thanks LAX18)

**Comment by mateoconlechuga** [comment]
If you delete the Cesium settings appvar it should automatically update.
