### ISSUE TITLE
Will not run some asm programs (for me)

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#73]
Whenever I try to run an asm or compiled ice program through Cesium, it forces me to clear my ram. However, if I call that asm program from a BASIC program and run that, it will run just fine.

**Comment by jcgter777** [comment]
Lol wut.

**Comment by jcgter777** [comment]
This is just you. Reinstall your OS, get a new calc, clear all memory, etc.

**Comment by LAX18** [comment]
What OS are you using @calclover2514 ?

This could be / kind of sounds like an outdated OS kind of thing.

**Comment by jcgter777** [comment]
Or like an asm program messed something up.

**Comment by calclover2514** [comment]
I have the newest OS and version of Cesium and done what you said (except get a new calc/reinstall OS) and the problem still persists. I do not especially care about running asm anyway, so I probably will just use it as is. Thanks

**Comment by jcgter777** [comment]
Back up your calculator, and fully mem clear. If you didn't use the force install OS or whatever, do it. Hold <kbd>2nd</kbd>+<kbd>del</kbd> (maybe <kbd>on</kbd>?) and press the reset button.

**Comment by jcgter777** [comment]
You should try to fix it still. 

Try force loading the OS and mem clearing a few times. 

2nd+del(+on) and press the reset button on the back. When the screen comes up, press clear a couple of times. Back up beforehand of course.

**Comment by calclover2514** [comment]
I have done this twice now and nothing has changed. I dont know what's happening, but I can't seem to fix it.

**Comment by mateoconlechuga** [comment]
Can you attach those files here?

**Comment by mateoconlechuga** [comment]
Just tested the latest master, both of those programs work fine for me.

**Comment by calclover2514** [comment]
This is still happening to me, although it is now happening only with large files with large names.

When I was writing ScriptCE, it worked when it was called SCE, but when I renamed it to SCRIPTCE, it stopped working.

I think I might have too many programs on my calc.

**Comment by mateoconlechuga** [comment]
I'm really going to need the program.
