### ISSUE TITLE
Some stuff, maybe ICE, maybe NOS, who knows

### ISSUE THREAD

**Issue by jcgter777** [mateoconlechuga/cesium#74]
After exiting an error (accidentally running an ICE source program), so like something invalid, calc displayed purple/green/blue/white junk, whited out and RAM cleared. I don’t know how to trigger this, and have not been able to reproduce. This may have had something to do with NOS. I can’t run programs from it, and after spamming a few times, it blacked out like it was going to RAM clear, but it launched into one of those memory error loops. I RAM cleared after, so it may not have had anything to do with it. I just feel so unlucky. I lost a ton of work from those two RAM clears. (Occurred within 3 minutes of each other)

Also, this was after I tried to put a sprite into my ICE source program. It wouldn’t compile, and then I ran the source, and then the glitch.

**Comment by calclover2514** [comment]
What version of ICE are you using? This kinda sounds like you are using v2.2.0.0, which is broken. Try building ICE from source and seeing if it happens anymore.
If that doesn't work, it could also be caused by a typo.
Could you show me the source?
