### ISSUE TITLE
Shortcuts are not working

### ISSUE THREAD

**Issue by mpdmonster2** [mateoconlechuga/cesium#75]
Holding ON and PRGM does not launch cesium. Holding ON and STAT does not turn calculator off. I have enabled keypad shortcuts in cesium settings. I am on a 84 plus CE on the latest software.

**Comment by mateoconlechuga** [comment]
They work fine. You are doing something wrong.

**Comment by mpdmonster2** [comment]
What am I doing wrong. Are you sure they work on the latest firmware?

**Comment by TheLastMillennial** [comment]
Yes, Cesium works fine on the latest firmware, OS, all the stuff.
Refer to the [Cemetech thread](https://www.cemetech.net/forum/viewtopic.php?p=273363#273363).
