### ISSUE TITLE
Freezing glitch, forces you to reset ram

### ISSUE THREAD

**Issue by moonpiedumplings** [mateoconlechuga/cesium#76]
With the latest version of cesium, sometimes when I send a file to my calculator, it will copy a file tha tis already on my calculator. When I then try to delete that copy, it freezes, with the only fix I've found so far is to push the reset button on the back. Will a hotfix be out soon?

**Comment by jcgter777** [comment]
just archive everything and ram reset. You lose nothing and you fix the problem.

**Comment by moonpiedumplings** [comment]
But there's a problem with that solution. Not all of my programs are in archive, as some programs need to be in ram to work. Also, this glitch freezes the calculator, not letting it do anything whatsoever, even connect to my computer.

**Comment by jcgter777** [comment]
Just archive them. Before you try to delete the duplicates, archive everything, then Ram clear. And why do you need programs to be in RAM? The latest OS lets you run archived programs, and without the asm( thing, from the homescreen.

**Comment by mateoconlechuga** [comment]
Don't use hidden files.

**Comment by tari** [comment]
To rephrase, "hidden files are known to cause problems when transferring files to or from the calculator."

This should be documented better (you say it is, but I can't find it), and possibly even (recognizing that many users don't read documentation) add a warning when users try to use it.

**Comment by moonpiedumplings** [comment]
Thank you.

**Comment by mateoconlechuga** [comment]
Rather late, but I fixed it so you are no longer allowed to hide/unhide archived programs. You must unarchive them before hiding them.
