### ISSUE TITLE
RAM CLEARED [v2.5.0 & v3.0.4 & v3.0.6]

### ISSUE THREAD

**Issue by JasonTheKitten** [mateoconlechuga/cesium#80]
So this bug reboots your calculator and wipes your un-archived programs.

How to reproduce:

1. Create a file called "prgmA" containing the command "Prompt A"
2. Open Cesium
3. Scroll to prgmA, open attribute menu, archive prgmA, close attribute menu
4. Press [zoom][2nd][quit][enter][2nd][quit][prgm][right]
5. Scroll up or down to prgmZTGP (auto-generated)
6. Press [enter][2nd][quit]
7. A menu comes up, scroll to prgmA, press zoom
8. The "TI-84 Plus CE 5.3.1.0058 RAM Cleared" screen pops up

I have not tested this on CEmu, but it works(?) on my calculator

If you forget to archive prgmA, replace these steps:
5. Scroll to prgmA instead of prgmZTGP
7. After scrolling, press [Alpha][Enter][Alpha][Alpha][Enter][Alpha] (Really a code repeated twice) instead of [zoom]

I have the start of a theory on why this works:
When you press zoom, the functionality of exiting the program editor is changed
You exit Cesium incorrectly, so the code is not removed
When you exit the editor again, you are booted to Cesium
Cesium is probably booted incorrectly, so it does not handle archive files correctly. Either that, a handle is still open somewhere.

**Comment by mateoconlechuga** [comment]
It happened because the cesium code wasn't where it was expected to be when the error handler popped the stack pointer. Fix simply copies cesium back into memory.

**Comment by JasonTheKitten** [comment]
Still happens for me on 3.0.6, it seems?

**Comment by JasonTheKitten** [comment]
Ok, when I get a chance

**Comment by JasonTheKitten** [comment]
Here is a video: https://github.com/JasonTheKitten/misc/raw/master/Dec%203%202018%203_23%20PM.webm

It's 3.0.6

**Comment by mateoconlechuga** [comment]
Do you not know how to use CEmu... But okay then

**Comment by JasonTheKitten** [comment]
I've got CEmu, but it is my real calculator I have the problem on.

**Comment by mateoconlechuga** [comment]
I was able to reproduce this in CEmu. I'll try to find out what is going on.

**Comment by mateoconlechuga** [comment]
okay, I swear I fixed it this time with c366679b1b86586073ec82bb16546ecdc1f9c9e5

will release when ready
