### ISSUE TITLE
Password Protection Nonfunctional When Connected to Computer + Password Bypass? [v3.0.6]

### ISSUE THREAD

**Issue by Stinggyray** [mateoconlechuga/cesium#84]
A weird issue I've encountered...
I was testing out the password feature out on the newest version of Cesium (3.0.6). It's a tiny bug, but I thought I'd put this out there that this tiny little bug exists.

So while I was testing it out, I found out that the password protect feature wasn't working. Pressing ON+STAT, it didn't power off and instead just displayed the password prompt. If you got the password wrong, the password prompt would just pop up again. So I disconnected it from my computer, and it worked as intended. Weird.

So ON+STAT doesn't power off the calculator when connected to your computer. Is this inherent of the method used to turn the calculator off, or is this just some bug relating to the code? Whatever, it's a tiny bug.

A side note: The calculator's password protect can be bypassed by initiating a hardware RAM clear. Should this be fixed, or left open as an intentional loophole, or is it literally impossible to close that loophole? (Maybe some clever use of archive / backup could do it. I don't know, I'm just some dude.)

**Comment by mateoconlechuga** [comment]
It's not the intention to be a protection mechanism. I threw it in there for fun :P

**Comment by jcgter777** [comment]
lol
