### ISSUE TITLE
Suggestion: Label jumping

### ISSUE THREAD

**Issue by beckadamtheinventor** [mateoconlechuga/cesium#88]
PHASM has a hook in the program editor which prints a list of all the labels in the program, and each list item jumps to it's respective label.
Why doesn't Cesium have this? :P

**Comment by mateoconlechuga** [comment]
Because this was as far as I got implementing it: https://github.com/mateoconlechuga/cesium/blob/master/src/hooks.asm#L79

**Comment by beckadamtheinventor** [comment]
Why not just port PHASM's code for it?
(It was written for an older assembler)
[InstantGoto.z80.txt](https://github.com/mateoconlechuga/cesium/files/3011064/InstantGoto.z80.txt)

**Comment by mateoconlechuga** [comment]
Added in 23eada33d98729eadbeff5bd11b606a6f106b3a5
