### ISSUE TITLE
Doesn't Appear In APPS Menu

### ISSUE THREAD

**Issue by matthew17754** [mateoconlechuga/cesium#9]
It is apparent that this shell does not appear in the APPS menu and needs to be launched from the "A" program in the PRGM menu. Will this program be ported as an APP soon or will it be a while? If so, I would recommend revising the readme instructions with anything regarding [apps] in order to avoid any confusion. Thanks. ;)

**Comment by mateoconlechuga** [comment]
Please stop asking things that you have no clue what you are asking. This is the development site; the readme is included *with the actual release*.

**Comment by mateoconlechuga** [comment]
To be clearer; yes it will eventually be an app. If you download the repository as it currently is and build it from the source, it is an app. It hasn't been released yet; so please read the readme that came with the actual download you used. (I imagine it was from [here](https://www.cemetech.net/programs/index.php?mode=file&path=/84pce/asm/shells/Cesium.zip)) Anywho, I apologize for being somewhat brash.

**Comment by matthew17754** [comment]
Oh. Wrong readme.md file. My bad. Sorry about that m8.
What is the expected release date for the next Cesium version?

**Comment by mateoconlechuga** [comment]
Haha don't worry about it I barely have a clue what I'm doing sometime. I hope to get it out within the next couple of weeks or so? Depends on how crazy school gets. Thanks for poking me about it; I tend to forget about these things...

**Comment by mateoconlechuga** [comment]
It does now! :D
