### ISSUE TITLE
Can't Unhide or Hide Programs

### ISSUE THREAD

**Issue by KeshavMadhavan** [mateoconlechuga/cesium#90]
I just got the new Gameboy Emulator for my Ti-84 Plus CE and after I was done setting it up I booted into Cesium to hide it. Once I got there I noticed it was already locked and it wouldn't let me unlock or hide it. I then went to another program and it also didn't let me unlock it or unhide it. Am I missing something? Thanks

**Comment by mateoconlechuga** [comment]
You cannot hide archived programs. You need to unarchive them, hide them, and rearchive them as needed.
