### ISSUE TITLE
Weird flashing thing

### ISSUE THREAD

**Issue by jcgter777** [mateoconlechuga/cesium#91]
I ran this fake mem reset program that uses textlib. I exited using <kbd>on</kbd> because that's the only way to exit that program. Then I just let it sit because I was typing something on the computer. Then I looked at the screen and in the middle bottom of the screen, in between the program list and the locked/archived icons, there was a flashing rectangle of black interwoven with weird colors.

**Comment by jcgter777** [comment]
I did it again and now the thing goes everywhere and it is in different shapes.

**Comment by mateoconlechuga** [comment]
so...... are you going to give me the program or am I just supposed to guess?

**Comment by jcgter777** [comment]
https://www.ticalculators.net/ti-84-plus-ce-fake-memory-clear/

I forgot sorry :P

**Comment by mateoconlechuga** [comment]
Hopefully fixed with 8205d99af42ae7fbb62b1e2651d3cf21eb42d477

**Comment by jcgter777** [comment]
Awesome! Thanks.
