### ISSUE TITLE
Garbage collect issue

### ISSUE THREAD

**Issue by TimmyTurner51** [mateoconlechuga/cesium#92]
Garbage collect causes an issue with cesium.
Once a garbage collect menu pops up, the menu is glitchy, and does not display properly.
After it's finished, the menu dissapears like it should, but the program names are glitchy.
Please fix this

Thanks, 
TimmyTurner62 @cemetech.net

**Comment by mateoconlechuga** [comment]
Probably fixed with 53a88a3741751421b43ca1e15b64420f68944e52, however there may still be a potential glitch. Hopefully should be fine.
