### ISSUE TITLE
Option to add "prgmNAME" to homescreen history after running a program

### ISSUE THREAD

**Issue by commandblockguy** [mateoconlechuga/cesium#93]
I find it convenient to be able to press enter to re-run the last program from the homescreen. It would be neat if there was an option in Cesium that would add the line "prgmNAME" to the homescreen history after running the program called NAME so that pressing enter on the homescreen would re-run that program.

**Comment by mateoconlechuga** [comment]
Unfortunately I don't see much utility in this. Can you explain a use case?

**Comment by commandblockguy** [comment]
I have a couple of TI-BASIC utility programs that I would need to use repeatedly in a short span of time. It's annoying to find them in the TI-OS list, and using Cesium's alpha search means that I can't rerun programs from the home screen.

**Comment by mateoconlechuga** [comment]
I still don't understand. You want to select the program in Cesium, and then run it from the homescreen?

**Comment by commandblockguy** [comment]
The program would be selected and run from Cesium, but added to the OS's history. That way if I need to exit Cesium to do calculations I can rerun the previous program by scrolling though the OS's history without having to reopen Cesium.
