### ISSUE TITLE
APD in random Assembly programs

### ISSUE THREAD

**Issue by beckadamtheinventor** [mateoconlechuga/cesium#94]
Cesium's APD will trigger randomly in some Assembly programs, ending the full screen graphics, but not the program itself.
This is only occurring with programs run from cesium. From the OS, they run  just fine.
For example, this happens in TileMapE v2, but not IcyCraft, despite both of them writing directly to appvars in RAM, and using similar techniques.

**Comment by mateoconlechuga** [comment]
Assembly programs are required to handle this themselves.
