### ISSUE TITLE
2nd quitting clears ram

### ISSUE THREAD

**Issue by slimeenergyreal** [mateoconlechuga/cesium#95]
With this program
"For(I,1,5):Input "F",C:End"
you can clear ram.
Steps:
1. Add that code to a basic program
2. Archive that program
3. Run from cesium
4. 2nd + Quit on the input

Inputs in loops and it being archived seem to be the problem.

**Comment by mateoconlechuga** [comment]
Man all the bugs are related to this one :(

**Comment by mateoconlechuga** [comment]
I can't reproduce this.

**Comment by mateoconlechuga** [comment]
Oh nope I got it hm.

**Comment by mateoconlechuga** [comment]
Fixed with 972bdd7e2442ddcf0b10547fa60fb3e525959360 hopefully
