### ISSUE TITLE
Very slow with new update; Jump to letter jumps to wrong spot or not at all.

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#97]
I tried out the new update and nothing noticeable appears to have changed except for a few new bugs:
* **Cesium v3.1** is noticeably slower than **Cesium v3.0.5**
* Jumping to a letter (aka. Jumping to programs starting with `J`) doesn't jump to the correct spot and sometimes doesn't jump at all

Unfortunately, because of these issues, I have reverted to **v3.0.5** until the bugs are fixed.

**Comment by mateoconlechuga** [comment]
You need to be more descriptive. "Cesium v3.1 is noticeably slower than Cesium v3.0.5" -> Can you expand on that?

**Comment by calclover2514** [comment]
The scrolling in **Cesium v3.1** is much slower than **Cesium 3.0.5**, as is color selection, among other things.
This makes Cesium's speed only a little better than TI-OS.

P.S. I tested this on my actual calc, not Cemu

**Comment by mateoconlechuga** [comment]
fixed with 3a440764f10b8c20cd9534c781e8e087db75b361
