### ISSUE TITLE
RAM CLEARED again

### ISSUE THREAD

**Issue by calclover2514** [mateoconlechuga/cesium#99]
Programs that would crash the calculator when run from cesium now crash it after program execution instead of before.

**Comment by mateoconlechuga** [comment]
Can you provide literally any details? Going to need more information.

**Comment by calclover2514** [comment]
I used to have some assembly programs crash upon execution in Cesium.
With version 3.0.5, ICE compiler runs perfectly, however, for some odd reason, it crashes on exiting if run from version 3.1.1.
Any program written ICE is having this same issue for me.
 P.S. I can't say this isn't an issue with my calc, but as it's happening only with the new version, it's a pretty safe assumption.

**Comment by mateoconlechuga** [comment]
Fixed and released with 3.1.2
